# -*- coding: utf-8 -*-
"""Per-area copy for the tracker-installation-<area> pages.

Each entry supplies genuinely area-specific content so the pages stop being
one template repeated 26 times. Fields:

  pc      postcodes, as displayed
  intro   opening paragraph of the .prose block (area-specific)
  recs    4 bullets - what we actually recommend here, and why
  outro   closing paragraph of the .prose block
  h2      heading for the new "what's different here" section
  p1, p2  the two body paragraphs of that section
  where   bullets - where we typically fit in this area
  p3      closing paragraph of that section
  faqs    area-specific Q&A pairs (3), appended to two tailored generics

No crime statistics or claims we cannot stand behind - local detail only.
"""

AREAS = {
"kensington": dict(
 pc="W8",
 intro="Kensington is a borough of stucco terraces, garden squares and mews houses, and almost none of it has a driveway. Owners here keep a Bentley or a Range Rover on a residents' bay on Phillimore Gardens or Campden Hill Road, or behind a gate in one of the mews off Kensington Church Street. That mix - high-value cars parked on the public kerb, in a permit zone, overnight - is exactly the situation an insurance-approved tracker and immobiliser is designed for.",
 recs=[("Meta Trak S5 with ADR tags","the driver-recognition tag matters most where a car sits on a public bay all night."),
       ("Tracker &amp; immobiliser package","the combination most Kensington insurers ask for on a car above &pound;100,000."),
       ("Autowatch Ghost II","no key, no fob, no visible module - popular with owners who don't want anything on show in a mews."),
       ("Dash camera with parking mode","kerbside cars in W8 pick up trolley and door damage more than anything else.")],
 outro="We fit across W8 - Kensington Church Street, Holland Street, Hornton Street, Phillimore Gardens, Campden Hill, Victoria Road and the Cornwall Gardens squares - and we hand over your insurance certificate on the day.",
 h2="Fitting a tracker in Kensington: what is different here",
 p1="The practical constraint in W8 is the Royal Borough's permit bays. We work on your car where it stands, so we need to be beside it for the duration - typically two to three hours for a tracker, longer for a tracker-and-immobiliser package. If your car is on a residents' bay we will usually ask you to bring a visitor permit or a scratch card for our van, or we work from a single yellow outside loading restriction hours. Tell us the street when you book and we will tell you which of those applies.",
 p2="The second thing that shapes the work here is the mews. A lot of Kensington's off-street parking is a converted coach house behind an arch on a cobbled lane - Kensington Court Place, Canning Place Mews, the lanes off Victoria Road. Those spaces are tight and often unlit, so we bring our own lighting and work with the doors open rather than trying to get the car out. If access is through a shared arch we will need the gate code or a resident to let us in.",
 where=["Residents' bays on Phillimore Gardens, Campden Hill Road and Victoria Road",
        "Mews and coach houses off Kensington Church Street and Victoria Road",
        "Underground and gated parking under the Cornwall Gardens and Lexham Gardens blocks",
        "Kensington High Street offices and the Kensington Palace Gardens end, by arrangement"],
 p3="If your car lives in a communal underground car park, check whether the building allows contractors - a few of the W8 blocks require the managing agent to be notified. We are happy to send our insurance details across if the porter asks for them.",
 faqs=[("Can you fit if my car is on a Kensington residents' bay?",
        "Yes - that is most of the work we do in W8. We need to be next to the car for two to three hours, so we will either use a visitor permit or scratch card, or work from a nearby single yellow outside the loading restriction. Tell us the street when you book and we will confirm which."),
       ("Will a tracker fit a mews house or coach house?",
        "Yes. Mews parking in Kensington is tight and often unlit, so we bring our own lighting and work with the car in place rather than moving it out onto the cobbles. We only need the doors to open."),
       ("Do you cover the whole of W8?",
        "Yes - Kensington Church Street, Holland Street, Hornton Street, Phillimore Gardens, Campden Hill, Victoria Road, Cornwall Gardens and Kensington High Street. We are based a few minutes away in Holland Park.")]),

"chelsea": dict(
 pc="SW3, SW10",
 intro="Chelsea parking splits three ways: the residents' bays on the streets off the King's Road, the mansion-block car parks along Fulham Road and Sloane Avenue, and the handful of houses on Cheyne Walk and Chelsea Embankment with a gate. Almost all of it is on show from the pavement. Owners here come to us because a Thatcham-approved tracker plus an immobiliser is the combination their insurer wants on a car that sleeps in public.",
 recs=[("Meta Trak S5 Deadlock","tracking plus deadlock immobilisation, which is what most SW3 insurers specify above &pound;75,000."),
       ("Meta Trak S7","self-monitored, app-first, and enough for a car kept behind a gate on Cheyne Walk."),
       ("Scorpion X or Ghost II immobiliser","added to an existing tracker where the insurer has asked for a second layer."),
       ("Front and rear dash camera","the King's Road side streets are narrow and Chelsea cars collect parked damage.")],
 outro="We fit throughout SW3 and SW10 - King's Road, Sloane Avenue, Cheyne Walk, Chelsea Embankment, Elystan Place, Markham Square and the Fulham Road blocks - and certification is handed over the same day.",
 h2="Fitting a tracker in Chelsea: what is different here",
 p1="The streets running north and south off the King's Road - Markham Street, Jubilee Place, Bywater Street - are narrow, and Kensington and Chelsea enforce them tightly. We plan Chelsea fittings for mid-morning where we can, after the school run and before the afternoon congestion, because we need the van beside the car and we would rather not be shuffling it. If you are in a mansion block off Fulham Road or Sloane Avenue with an allocated space, that is the easiest job we do - covered, lit, and no permit involved.",
 p2="Chelsea also has a lot of underground residents' parking, and those car parks are where we do some of our best work: out of the weather, out of sight, and we can take the time to route the loom properly rather than working around a rain shower. What we do need is confirmation that the building allows a contractor in. Some of the Chelsea Harbour and Sloane Avenue blocks want the managing agent told in advance and will ask the porter to check our insurance.",
 where=["Residents' bays on Markham Square, Elystan Place and the King's Road side streets",
        "Mansion-block car parks along Fulham Road, Sloane Avenue and Chelsea Harbour",
        "Gated frontages on Cheyne Walk and Chelsea Embankment",
        "Chelsea and Brompton offices, by arrangement"],
 p3="Roadworks around the King's Road and Sloane Square change often. If your street is closed on the day we can usually work from an adjacent street as long as the car can be moved there legally - we will call you the morning of the fitting either way.",
 faqs=[("Can you fit in a Chelsea mansion-block car park?",
        "Yes, and it is our preferred option in SW3 - covered, lit and no permit needed. Some blocks off Fulham Road and Sloane Avenue ask for the managing agent to be notified first, and the porter may want to see our insurance. We can send those documents over in advance."),
       ("Do I need to move my car off the King's Road side streets?",
        "No. We work on the car where it stands. We do need the van beside it for two to three hours, so we normally book Chelsea fittings mid-morning to stay clear of the busiest periods."),
       ("Which postcodes around Chelsea do you cover?",
        "SW3 and SW10 in full, and we are on neighbouring Fulham SW6, Belgravia SW1 and South Kensington SW7 most weeks.")]),

"knightsbridge": dict(
 pc="SW1, SW7",
 intro="Knightsbridge has more underground parking per square mile than anywhere else we work. Cars here live in the car parks beneath the Brompton Road and Sloane Street blocks, in the garages under Hans Place and Montpelier Square, or on a valet-managed level with a porter holding the keys. It changes the security question: the car is rarely on a public kerb, but the keys often pass through several hands, which is precisely what a driver-recognition tag is for.",
 recs=[("Meta Trak S5 with ADR driver tags","the tag stays with you, not with the porter or valet, so an unauthorised move raises an alert."),
       ("Autowatch Ghost II","a CAN-bus immobiliser with no key and nothing to hand over - ideal where a third party parks the car."),
       ("Tracker &amp; immobiliser package","what most insurers specify for the values typically kept in SW1 and SW7."),
       ("Dash camera with parking mode","low-speed contact in a tight underground bay is the most common claim we see here.")],
 outro="We fit across Knightsbridge - Brompton Road, Sloane Street, Hans Place, Montpelier Square, Beauchamp Place, Cadogan Place and the Knightsbridge Green blocks - with certification handed over on the day.",
 h2="Fitting a tracker in Knightsbridge: what is different here",
 p1="Nearly every Knightsbridge fitting starts with a phone call to a concierge. The underground car parks here are managed, and most of them need the resident to authorise a contractor before the barrier goes up. Height is the other consideration - a number of the SW1 and SW7 car parks have a two-metre limit, which our van clears, but if yours is lower we bring the kit down in cases and work on foot. Tell us the block when you book and we will check the access before we arrive.",
 p2="Where the car is valet-parked or moved by building staff, the security brief changes. A tracker on its own will tell you the car has moved but not whether the move was authorised. That is why we fit Meta Trak S5 with driver tags here more than anywhere else: the tag lives on your own keyring, so a legitimate move by you is silent and a move without the tag is not. For owners who would rather not hand over anything at all, the Ghost II sits on the CAN bus with no fob and no visible module.",
 where=["Underground car parks off Brompton Road, Sloane Street and Knightsbridge Green",
        "Garages and gated frontages on Hans Place, Montpelier Square and Cadogan Place",
        "Valet-managed levels under the larger SW1 and SW7 blocks",
        "Residents' bays on Beauchamp Place and the Ennismore Gardens side streets"],
 p3="If you are between properties or your building will not admit a contractor, we can fit at our Holland Park base instead - it is a fifteen-minute drive from Knightsbridge and there is no permit or barrier to negotiate.",
 faqs=[("My car is in an underground car park - can you still fit?",
        "Yes, and most of our Knightsbridge work is underground. We need the resident to authorise us with the concierge beforehand, and we will check the height restriction when you book. If the car park is too low for the van we bring the kit down in cases."),
       ("The building valet parks my car. Does that change what I need?",
        "It does. A tracker alone tells you the car moved, not whether the move was authorised. In that situation we normally fit Meta Trak S5 with ADR driver tags - the tag stays on your keyring, so your own movements are silent and anyone else's are not."),
       ("Can you fit somewhere other than my building?",
        "Yes. If your car park will not admit contractors we can fit at our Holland Park base, about fifteen minutes from Knightsbridge, or at your office if that is easier.")]),

"belgravia": dict(
 pc="SW1",
 intro="Belgravia is Grosvenor Estate land, and it shows in the parking: formal garden squares with residents' bays around the perimeter, and behind them a dense network of mews - Eaton Mews, Kinnerton Street, Wilton Row - where the actual off-street parking is. Cars here are high in value and low in mileage, often sitting for weeks at a time, which brings its own considerations for a tracker installation.",
 recs=[("Meta Trak S5 with ADR tags","standard specification for the values kept around Eaton and Chester Square."),
       ("Autowatch Ghost II","nothing visible, nothing to hand over - suited to a car left in a mews for long periods."),
       ("Tracker &amp; immobiliser package","the layered specification most Belgravia policies now ask for."),
       ("Battery conditioning advice","a car that sits needs a healthy battery for the tracker to report reliably - we will flag it if yours is marginal.")],
 outro="We cover Belgravia in full - Eaton Square, Chester Square, Wilton Crescent, Lowndes Square, Kinnerton Street and the Eaton and Grosvenor mews - and certification is issued the same day.",
 h2="Fitting a tracker in Belgravia: what is different here",
 p1="The single most useful thing to know about tracker installation in Belgravia is what happens to a car that does not move. Plenty of the cars we fit here cover a few hundred miles a year. A hard-wired tracker draws a small standing current, and on a car that already sits for six weeks between drives, a battery that was merely tired becomes a flat one. We check battery health as part of every Belgravia fitting and we will tell you honestly if a conditioner or a new battery should come first - it is cheaper than a recovery call.",
 p2="Access is the other Belgravia peculiarity. The mews are private, narrow and often cobbled, with an arch at one end that our van will not fit through. We are used to it: we park on the square, walk the kit in, and work on the car where it stands. Where the parking is a residents' bay on Eaton or Chester Square we will need a visitor permit, and the Grosvenor Estate blocks generally want the managing agent told that a contractor is coming.",
 where=["Residents' bays around Eaton Square, Chester Square and Lowndes Square",
        "Mews and coach houses off Kinnerton Street, Wilton Row and Eaton Mews",
        "Underground parking under the Grosvenor Estate blocks",
        "Gated frontages on Wilton Crescent and Belgrave Square"],
 p3="If the car has not run for a while, leave us the key rather than trying to start it before we arrive - we would rather assess the battery cold and give you an accurate picture than have it jump-started an hour beforehand.",
 faqs=[("My car barely moves. Will a tracker drain the battery?",
        "A hard-wired tracker draws a small standing current, which matters on a car that sits for weeks - and a lot of Belgravia cars do. We check battery health at every fitting here and will tell you if a conditioner or a replacement battery should come first."),
       ("Can you get into the Belgravia mews?",
        "The arches are too low for our van, so we park on the square and walk the kit in. That is normal for us in SW1 and it does not add to the cost or the time."),
       ("Do you need permission from the estate?",
        "For a residents' bay we will need a visitor permit from you. For the Grosvenor Estate blocks the managing agent usually wants to be told a contractor is coming - we can send our insurance details over if they ask.")]),

"mayfair": dict(
 pc="W1",
 intro="Mayfair has the least kerbside parking of anywhere we cover and the highest concentration of cars worth protecting. Most of what we fit here lives in an underground car park - beneath the Park Lane and Grosvenor Square blocks, in the commercial car parks off Audley Street, or in one of the mews garages on Adams Row, Reeves Mews and Balfour Mews. Access, not the installation itself, is usually the thing that needs planning.",
 recs=[("Meta Trak S5 with ADR driver tags","the specification for the values normally kept in W1, and the tag handles valet movement."),
       ("Autowatch Ghost II","no fob, no visible module, nothing a valet or attendant needs to be given."),
       ("Tracker &amp; immobiliser package","the layered protection Mayfair insurers ask for above &pound;150,000."),
       ("Dash camera with parking mode","tight commercial car parks are where most Mayfair damage claims start.")],
 outro="We fit across Mayfair - Mount Street, Berkeley Square, Grosvenor Square, Park Lane, South Audley Street, Curzon Street and the Grosvenor mews - and hand over insurance certification on the day.",
 h2="Fitting a tracker in Mayfair: what is different here",
 p1="Two things govern a Mayfair fitting. The first is the car park barrier: most W1 underground parking is managed, and we need you to clear us with the concierge or the operator before we arrive. The second is height. Several of the older Mayfair car parks are under 1.9 metres, which our van will not clear, so we bring the equipment down in cases and work on foot. Neither is a problem if we know in advance - tell us the building or the car park name when you book and we will check it.",
 p2="Mayfair is also the area where cars are most often moved by someone other than the owner: hotel valets, a chauffeur, a member of staff, an attendant shuffling a level. A plain tracker reports the movement but cannot tell you whether it was authorised, which is why driver-recognition tags do more work here than anywhere else. If you would rather not hand anything over at all, a Ghost II immobiliser sits on the CAN bus with no fob and no module to find, and the car simply will not drive without the sequence.",
 where=["Underground car parks off Park Lane, Grosvenor Square and South Audley Street",
        "Mews garages on Adams Row, Reeves Mews and Balfour Mews",
        "Hotel and commercial car parks around Curzon Street and Berkeley Square",
        "Mayfair offices and private members' club parking, by arrangement"],
 p3="If your Mayfair parking cannot admit a contractor at all - and a few of the hotel car parks will not - we can fit at our Holland Park base, twenty minutes west, or at a second address if you keep the car outside W1 at weekends.",
 faqs=[("Can you fit in a Mayfair underground car park?",
        "Yes, and most W1 fittings are underground. We need to be cleared with the concierge or the car park operator first, and we check the height limit when you book - several older Mayfair car parks are under 1.9 metres, in which case we walk the kit down."),
       ("Valets and my chauffeur both move the car. What should I fit?",
        "Meta Trak S5 with ADR driver tags. The tag stays on your keyring, so your own movements are silent while a move without it raises an alert. If you would rather hand over nothing, a Ghost II immobiliser has no fob at all."),
       ("Is there kerbside parking you can work from in Mayfair?",
        "Very little, and Westminster enforces W1 tightly. If your car is on a meter or a residents' bay we will plan around the restriction hours, but underground or mews parking is far easier and we would steer you there.")]),

"westminster": dict(
 pc="SW1",
 intro="Westminster covers a lot of ground and the parking changes with it - the riverside mansion blocks at Millbank, the garden squares of Pimlico, the terraces behind Victoria, and the streets around Smith Square. What it has in common is Westminster City Council's controlled parking, which operates longer hours than most London boroughs and shapes how a mobile fitting has to be scheduled.",
 recs=[("Meta Trak S7","self-monitored and app-first - a good fit for a car kept in a Pimlico block with its own gate."),
       ("Meta Trak S5 with ADR tags","where the car sits on a public bay and the policy asks for driver recognition."),
       ("Tracker &amp; immobiliser package","the specification we fit most often across SW1."),
       ("Dash camera with parking mode","Westminster's bays are tight and closely parked; parking mode catches what happens while you are away.")],
 outro="We fit throughout Westminster and SW1 - Pimlico, Victoria, Millbank, Smith Square, Vincent Square, Warwick Square and the Grosvenor Road blocks - with certification handed over on the day.",
 h2="Fitting a tracker in Westminster: what is different here",
 p1="Westminster's controlled parking zones run later into the evening and further into the weekend than most of London, which matters when a job takes two to three hours. In practice we do one of three things: work from a visitor permit or scratch card you supply, work from a single yellow outside the loading restriction, or - much the easiest - fit in your block's own car park if you have a space. If you are in one of the Millbank or Grosvenor Road blocks with underground parking, that is the option we will suggest.",
 p2="The other Westminster factor is event and security closures. Streets around Parliament, Victoria and Millbank close at short notice for state occasions, demonstrations and works, and there is no warning we can plan around a week out. We call every Westminster customer on the morning of the fitting to confirm access is clear. If the street is shut we will either move to an adjacent street, if your car can legally be moved there, or reschedule at no charge.",
 where=["Underground and gated parking in the Millbank and Grosvenor Road blocks",
        "Residents' bays around Warwick Square, Vincent Square and Pimlico's garden squares",
        "Streets behind Victoria and around Smith Square, outside restriction hours",
        "Westminster offices and serviced apartment parking, by arrangement"],
 p3="If you work in SW1 but keep the car elsewhere, we can just as easily fit at the other address - a fair number of our Westminster customers have us come to a home in Surrey at the weekend instead.",
 faqs=[("Westminster's parking restrictions run late. How do you work around them?",
        "Three ways: a visitor permit or scratch card you provide, a single yellow outside the loading restriction, or your block's own car park if you have a space. The last is much the easiest and we will suggest it where it exists."),
       ("What happens if my street is closed for an event?",
        "We call every Westminster customer on the morning of the fitting to check access. If the street is shut we move to an adjacent street where the car can legally be parked, or we reschedule at no charge."),
       ("Do you cover the whole of SW1?",
        "Yes - Pimlico, Victoria, Millbank, Smith Square, Vincent Square and Warwick Square, plus neighbouring Belgravia and Knightsbridge.")]),

"notting-hill": dict(
 pc="W11",
 intro="Notting Hill's defining feature for our purposes is the communal garden square. Cars on Lansdowne Road, Elgin Crescent and Ladbroke Grove are parked on the street, in a permit bay, on roads that fill completely by early evening - and on Saturdays the Portobello market takes several of them out of use entirely. We fit around all of it, and we are based a few streets away in Holland Park.",
 recs=[("Meta Trak S5 with ADR tags","the right specification for a valuable car that sleeps on a public W11 bay."),
       ("Tracker &amp; immobiliser package","our most-fitted combination in Notting Hill."),
       ("Autowatch Ghost II","for owners who want no visible deterrent and nothing extra on the keyring."),
       ("Front and rear dash camera","narrow, densely parked streets - most W11 claims we see are parked damage.")],
 outro="We fit across W11 - Ladbroke Grove, Portobello Road, Elgin Crescent, Lansdowne Road, Kensington Park Road, Westbourne Grove and Clarendon Road - and issue certification the same day.",
 h2="Fitting a tracker in Notting Hill: what is different here",
 p1="Saturday is the thing to plan around. The Portobello market closes Portobello Road and constrains everything feeding into it, and the streets that are still open fill with visitor traffic from mid-morning. We will fit in Notting Hill on a Saturday if that is what suits you, but we will suggest a weekday morning, and we will ask which end of your street you are parked on. Carnival weekend in late August is the other exception - large parts of W11 are inaccessible and we do not book fittings inside the closure area.",
 p2="The streets themselves are narrow and steeply cambered in places, and the residents' bays are full by evening. That is a practical argument for booking a morning slot: there is space to work beside the car, and we are not obstructing a street that has no give in it. If you have access to one of the communal garden squares or a gated garage off Clarendon Road or Lansdowne Walk, say so when you book - it makes for an easier, drier fitting.",
 where=["Residents' bays on Lansdowne Road, Elgin Crescent and Kensington Park Road",
        "Communal garden square parking, where residents have access",
        "Gated garages and mews off Clarendon Road and Lansdowne Walk",
        "Westbourne Grove and Notting Hill Gate offices, by arrangement"],
 p3="We are based on Addison Avenue, a few minutes from Notting Hill Gate, so W11 is the area we can usually reach soonest - often the same week, and sometimes the next day if a slot opens.",
 faqs=[("Can you fit on a Saturday during the Portobello market?",
        "We can, but we would suggest a weekday morning. The market closes Portobello Road and constrains the streets feeding into it, and the bays fill with visitor traffic from mid-morning. We do not book fittings inside the Carnival closure area in late August."),
       ("The bays on my street are always full. Is that a problem?",
        "It is the main reason we prefer morning slots in W11 - there is room to work beside the car and we are not blocking a narrow street. If you have garden square or gated garage access, tell us and we will use it."),
       ("How quickly can you get to Notting Hill?",
        "Faster than anywhere else we cover - we are on Addison Avenue in Holland Park, a few minutes away. Often the same week, sometimes the next day.")]),

"holland-park": dict(
 pc="W11, W14",
 intro="Holland Park is where we are based - our address is Addison Avenue, W11 4QR. The area's parking is unusually good for central London: wide streets on the Norland Estate, gated garages behind Royal Crescent and Addison Avenue, and off-street space on the larger Holland Park Avenue houses. It also means we can generally reach a Holland Park customer sooner than anyone else.",
 recs=[("Meta Trak S5 with ADR tags","for a car parked on the avenue or a residents' bay overnight."),
       ("Meta Trak S7","enough where the car is behind a gate on the Norland Estate."),
       ("Tracker &amp; immobiliser package","the specification most W11 and W14 policies ask for above &pound;100,000."),
       ("Apple CarPlay and dash camera","we fit a lot of both locally, often on the same visit as the security work.")],
 outro="We fit throughout Holland Park - Addison Avenue, Holland Park Avenue, Norland Square, Royal Crescent, Portland Road, Clarendon Cross and the Holland Park roads - and certification is issued the same day.",
 h2="Fitting a tracker in Holland Park: what is different here",
 p1="Being local changes what we can offer. Holland Park customers get the shortest lead times we have, and if something needs a second look - a warning light after a fitting, a question about the app, a tag that needs pairing - we can be back the same day rather than fitting you into a route. We also do a fair amount of combined work here: a tracker and an Apple CarPlay retrofit on the same visit, which is more efficient than two separate appointments and means the trim only comes off once.",
 p2="Parking is genuinely easier in W11 and W14 than in most of the areas we cover. The Norland Estate streets are wide, a good number of the Addison Avenue and Royal Crescent houses have a gated garage or a hardstanding, and there is more room to work beside a car than there is in Chelsea or Mayfair. Where you are on a residents' bay we will still need a visitor permit or a scratch card, and Kensington and Chelsea enforce W11 in the usual way.",
 where=["Gated garages and hardstandings on Addison Avenue, Royal Crescent and Norland Square",
        "Residents' bays along Holland Park Avenue and Portland Road",
        "Off-street parking on the larger Holland Park and Abbotsbury Road houses",
        "Our own Addison Avenue base, if you would rather bring the car to us"],
 p3="If it suits you better, you can bring the car to us on Addison Avenue instead of us coming out - it is the one area where that is often the simpler option.",
 faqs=[("Are you actually based in Holland Park?",
        "Yes - Addison Avenue, Holland Park, London W11 4QR. It is a mobile service, so we still come to you, but Holland Park gets our shortest lead times and we can come back the same day if anything needs a second look."),
       ("Can I bring the car to you instead?",
        "In Holland Park, yes, and it is often simpler. Anywhere else we would come to you - we are a mobile service and there is no public workshop."),
       ("Can you fit a tracker and CarPlay on the same visit?",
        "Yes, and we do it often locally. Combining them means the trim comes off once and you only lose the car for one appointment.")]),

"south-kensington": dict(
 pc="SW7",
 intro="South Kensington is stucco terraces converted into flats, arranged around big garden squares - Onslow, Thurloe, Egerton, Queen's Gate. Very little of it has off-street parking. Cars sit on residents' bays around the square perimeters or on the streets running down to Cromwell Road, which makes a Thatcham-approved tracker with an immobiliser the standard specification here.",
 recs=[("Meta Trak S5 with ADR tags","for a car on a public bay in a busy, well-trafficked SW7 street."),
       ("Tracker &amp; immobiliser package","the combination most South Kensington insurers now require."),
       ("Autowatch Ghost II","where an owner wants a second layer with nothing visible and no extra fob."),
       ("Dash camera with parking mode","the square perimeters are tightly parked and door damage is common.")],
 outro="We fit across SW7 - Onslow Square, Onslow Gardens, Thurloe Square, Queen's Gate, Egerton Gardens, Cromwell Road and the Old Brompton Road streets - with certification handed over on the day.",
 h2="Fitting a tracker in South Kensington: what is different here",
 p1="The garden squares are the whole story here. Parking runs round the perimeter of Onslow, Thurloe and Egerton in residents' bays, and those bays are busy from early evening onwards. A morning appointment gives us room to work beside the car without holding up a narrow one-way. We will need a visitor permit or a scratch card from you, or we work from a single yellow outside the loading restriction - tell us the square and we will tell you which applies.",
 p2="SW7 also has a lot of converted mansion flats, and the practical consequence is that the car and the owner are often not in the same place. We do not need you present for the whole fitting - we need the key, access to the car, and a phone number. Plenty of our South Kensington customers hand over the key, go to work, and collect the app walkthrough and the insurance certificate at the end. Where the block has a porter we can leave the key with them if you prefer.",
 where=["Residents' bays around Onslow, Thurloe and Egerton squares",
        "Streets running down to Cromwell Road and Old Brompton Road",
        "The handful of gated garages behind the Queen's Gate terraces",
        "Underground parking under the newer SW7 developments"],
 p3="Cromwell Road traffic is heaviest mid-afternoon. If your car is parked on or immediately off it, an earlier slot will be a calmer job for everyone.",
 faqs=[("Do I need to be there for the whole fitting?",
        "No. We need the key, access to the car and a phone number. Many South Kensington customers hand the key over and go to work - we do the app walkthrough and hand over the insurance certificate at the end, or leave the key with the porter."),
       ("Can you fit on an Onslow or Thurloe Square residents' bay?",
        "Yes, that is most of our SW7 work. We will need a visitor permit or scratch card from you, or we work from a single yellow outside the loading restriction. Morning slots are easier on those one-way streets."),
       ("Which streets do you cover in SW7?",
        "All of them - Onslow Square and Gardens, Thurloe Square, Queen's Gate, Egerton Gardens, Cromwell Road and the Old Brompton Road side streets.")]),

"fulham": dict(
 pc="SW6",
 intro="Fulham is where central London starts having driveways again. The streets around Parsons Green and Hurlingham are family houses, many with a hardstanding or a garage, and the cars reflect it - Range Rovers, Q7s, X5s and Macans doing school runs and motorway miles rather than sitting still. That changes the security priorities slightly: keyless entry theft from a driveway is the risk we are asked about most in SW6.",
 recs=[("Meta Trak S5 Deadlock","tracking plus deadlock immobilisation, the strongest answer to a keyless relay attack on a driveway."),
       ("Autowatch Ghost II","stops the car being driven away even if the thieves have cloned the signal."),
       ("Tracker &amp; immobiliser package","the specification most SW6 insurers ask for on a modern keyless SUV."),
       ("Front and rear dash camera with parking mode","useful on a driveway that opens straight onto the street.")],
 outro="We fit throughout SW6 - Fulham Road, Parsons Green, Hurlingham, Bishops Park, Munster Village, Fulham Palace Road and the Peterborough Estate - and hand over certification on the day.",
 h2="Fitting a tracker in Fulham: what is different here",
 p1="Driveway parking makes for the easiest fittings we do, and it also explains what SW6 owners actually worry about. Keyless relay theft targets exactly this situation: a modern SUV parked a few metres from a front door, with the keys inside the house and close enough to the wall for the signal to be picked up and repeated. A tracker will tell you the car has gone. An immobiliser is what stops it going. In Fulham we fit the two together more often than we fit a tracker on its own, and that is the honest recommendation for a keyless car on a driveway.",
 p2="Practically, a driveway or garage fitting means we are out of the traffic, out of the weather and able to take our time routing the loom where it should go rather than where it is quickest. It also means no permit. Where you are on a residents' bay - the Munster Village streets and much of Fulham Road - we work as we do elsewhere in London, with a visitor permit or outside the loading restriction. Match-day closures around Craven Cottage are worth mentioning when you book.",
 where=["Driveways and garages around Parsons Green, Hurlingham and the Peterborough Estate",
        "Residents' bays in Munster Village and along Fulham Road",
        "Mansion-block parking near Bishops Park and Fulham Palace Road",
        "Fulham offices and business parking, by arrangement"],
 p3="If your keys live on a hook by the front door, move them - a signal-blocking pouch and a bit of distance from the wall costs nothing and makes a relay attack harder before we fit anything at all.",
 faqs=[("My car is keyless and sits on the driveway. What do I actually need?",
        "A tracker and an immobiliser together. Relay theft copies the key signal from inside the house, so a tracker tells you the car has gone but an immobiliser is what stops it going. That combination is what we fit most in SW6, and it is what most insurers here ask for."),
       ("Is a driveway fitting easier?",
        "Considerably - no permit, out of the traffic and the weather, and we can take the time to route the wiring properly. If you have a garage, better still."),
       ("Do match days affect getting to me?",
        "They can, around Craven Cottage and Fulham Palace Road. Mention it when you book and we will schedule around the fixture.")]),

"hampstead": dict(
 pc="NW3",
 intro="Hampstead is hills, narrow lanes and private drives. Cars here are often behind a gate on Frognal, up a steep drive off Heath Street, or in a garage on one of the roads running down to the Heath - and the roads themselves are some of the tightest we work on. It is a different job from a flat central London bay, and worth knowing about before you book.",
 recs=[("Meta Trak S5 Deadlock","tracking with deadlock immobilisation, the specification most NW3 insurers ask for."),
       ("Autowatch Ghost II","no visible module and no fob, which suits a car kept behind a gate."),
       ("Tracker &amp; immobiliser package","our most-fitted combination for Hampstead driveways."),
       ("Dash camera with parking mode","the lanes are narrow and passing damage on a kerbside car is common.")],
 outro="We fit across NW3 - Heath Street, Church Row, Frognal, Fitzjohn's Avenue, Well Walk, Downshire Hill and the roads bordering the Heath - with certification handed over the same day.",
 h2="Fitting a tracker in Hampstead: what is different here",
 p1="Access is the Hampstead variable. A good number of NW3 drives are steep, gravelled and narrower than they look, and some of the lanes off Heath Street will not take a van at all. We are used to walking the kit in where we have to, but it is worth telling us what the approach looks like when you book - whether there is a gate, how steep the drive is, and whether there is anywhere for the van within a hundred metres or so. It saves us both a wasted slot.",
 p2="Hampstead's other characteristic is the number of cars kept in a garage and used occasionally. Those need the same battery conversation we have in Belgravia: a hard-wired tracker draws a standing current, and on a car that sits between drives, that can be the difference between starting and not. We check battery health as part of the fitting and will say if a conditioner is the sensible first step. Garage fittings are otherwise the best conditions we get - dry, private and unhurried.",
 where=["Private drives and garages off Frognal, Fitzjohn's Avenue and Redington Road",
        "Kerbside and permit parking on Heath Street, Church Row and Downshire Hill",
        "Houses backing onto the Heath, on the Well Walk and East Heath side",
        "Underground parking in the newer NW3 developments"],
 p3="Hampstead and the roads around the Heath ice over before the rest of London. In winter we will happily reschedule a steep-drive fitting rather than take a van up it on a bad morning.",
 faqs=[("My drive is steep and narrow. Can you still fit?",
        "Usually yes - we walk the kit in where the van cannot get up. Tell us what the approach looks like when you book: gate, gradient, and whether there is anywhere for the van within a hundred metres or so."),
       ("The car lives in a garage and only comes out occasionally. Anything to know?",
        "Yes - a hard-wired tracker draws a small standing current, which matters on a car that sits. We check battery health at the fitting and will tell you if a conditioner should come first."),
       ("Do you cover the streets right by the Heath?",
        "Yes - Well Walk, East Heath Road, Downshire Hill and the roads bordering the Heath, along with the rest of NW3.")]),

"st-johns-wood": dict(
 pc="NW8",
 intro="St John's Wood has the best parking of anywhere we cover in central London. The Avenue Road and Hamilton Terrace houses have in-and-out drives, several have underground garages, and the newer developments around Lord's have proper resident car parks. Cars here are large, valuable and usually parked off the public highway - which shifts the security question from visibility to whether the car can be driven away.",
 recs=[("Autowatch Ghost II","stops the car being driven off a private drive even with a relayed key signal."),
       ("Meta Trak S5 Deadlock","tracking and deadlock immobilisation in one approved system."),
       ("Tracker &amp; immobiliser package","the specification NW8 insurers ask for on the values kept here."),
       ("Dash camera with parking mode","in-and-out drives open onto busy roads; parking mode covers the gate line.")],
 outro="We fit throughout NW8 - Avenue Road, Hamilton Terrace, Abbey Road, Carlton Hill, Elm Tree Road, Wellington Road and the developments around Lord's - and issue certification the same day.",
 h2="Fitting a tracker in St John's Wood: what is different here",
 p1="Because so much NW8 parking is private, the threat that matters is not someone spotting the car - it is someone getting it off the drive. Keyless relay theft is the method, and a large, in-demand SUV sitting a few metres from a hallway key hook is the ideal target. That is why the immobiliser side of the work gets more attention here than the tracker side. A Ghost II or a Meta Trak S5 Deadlock means a relayed signal gets the thief into the car and no further, which is the outcome you want.",
 p2="The fittings themselves are straightforward. In-and-out drives give us room to park beside the car and work without obstructing anything, underground garages are better still, and there is no permit to arrange in most of NW8. Where you are in one of the mansion blocks along Wellington Road or near Lord's, we will need to be cleared with the porter first. Test-match traffic around Lord's is worth flagging when you book - it changes the approach roads for the day.",
 where=["In-and-out drives on Avenue Road, Hamilton Terrace and Carlton Hill",
        "Underground garages on the larger NW8 houses",
        "Resident car parks in the developments around Lord's and Wellington Road",
        "Abbey Road and Elm Tree Road kerbside, where drives are not available"],
 p3="If you keep more than one car at the address - and a lot of NW8 households do - tell us when you book. Fitting two on the same visit is cheaper and quicker than two separate appointments.",
 faqs=[("The car is on a private drive. Do I still need a tracker?",
        "A tracker is what your insurer certifies and what recovers the car, but on a private drive the immobiliser is doing the harder work. Relay theft gets a thief into the car; a Ghost II or an S5 Deadlock means it goes no further. We normally fit both here."),
       ("Can you do two cars at the same address?",
        "Yes, and it is cheaper and quicker than two visits. A lot of NW8 households have us do exactly that - tell us both vehicles when you book."),
       ("Does Lord's affect access?",
        "On test-match and international days the approach roads change and it gets slow. Mention it when you book and we will schedule around the fixture list.")]),

"primrose-hill": dict(
 pc="NW1, NW3",
 intro="Primrose Hill is a small, tight grid of Victorian terraces - Regent's Park Road, Chalcot Square, Gloucester Crescent, Fitzroy Road - with almost no off-street parking and permit bays that are full by early evening. The cars are valuable, the streets are narrow, and there is very little slack in either. Fittings here need a bit more planning than most.",
 recs=[("Meta Trak S5 with ADR tags","the right specification for a car parked on a public NW1 bay overnight."),
       ("Tracker &amp; immobiliser package","our most-fitted combination locally."),
       ("Autowatch Ghost II","nothing visible, no extra fob - suited to a terrace with no garage."),
       ("Front and rear dash camera","tight, densely parked streets, and most local claims we see are parked damage.")],
 outro="We fit across Primrose Hill - Regent's Park Road, Chalcot Square, Chalcot Road, Gloucester Crescent, Fitzroy Road, Princess Road and the streets down to Camden - with certification handed over on the day.",
 h2="Fitting a tracker in Primrose Hill: what is different here",
 p1="The bays fill up. By six in the evening there is little space on Chalcot Road or Fitzroy Road, and on a weekend the hill itself draws visitors who take up what is left. We book Primrose Hill fittings for the morning almost without exception - it is the only reliable way to have room to work beside the car without blocking a single-lane street. If you can tell us roughly where you tend to be parked, we will plan the van position around it.",
 p2="Camden's controlled parking applies, so we will need a visitor permit or a scratch card from you, or we work from a single yellow outside the loading restriction. Loading restrictions here are shorter than Westminster's, which helps. The other thing worth knowing is that a number of Primrose Hill houses have a converted basement or a rear yard reached through a side passage - if the car can go in there it is a much better fitting environment, and we would rather use it.",
 where=["Permit bays on Chalcot Road, Fitzroy Road and Princess Road",
        "Regent's Park Road kerbside, outside restriction hours",
        "Rear yards and hardstandings reached from the side passages",
        "The handful of garages off Gloucester Crescent and Oppidans Road"],
 p3="If parking on your street is genuinely impossible on the day, we can fit at a second address or at our Holland Park base - and in Primrose Hill that is a conversation we have reasonably often.",
 faqs=[("The bays on my street are always full. Can you still fit?",
        "Yes, but we will book you a morning slot - by early evening there is no room on Chalcot or Fitzroy Road to work beside the car. Tell us roughly where you park and we will plan the van position."),
       ("Do you need a permit from me?",
        "Camden's controlled parking applies, so either a visitor permit or a scratch card from you, or we work from a single yellow outside the loading restriction. The restriction hours here are shorter than Westminster's, which helps."),
       ("What if there is nowhere to park at all on the day?",
        "We can fit at a second address or at our Holland Park base. In Primrose Hill that comes up often enough that we plan for it.")]),

"barnes": dict(
 pc="SW13",
 intro="Barnes feels more like a village than a London suburb and parks like one. The houses along Castelnau, Church Road and the streets around Barnes Common mostly have a driveway or a hardstanding, the cars are family SUVs and estates, and the roads are quiet enough that a fitting is rarely complicated by traffic. The risk profile is a driveway one - relay theft, not opportunistic street crime.",
 recs=[("Meta Trak S5 Deadlock","tracking with deadlock immobilisation, which is what stops a relayed key working."),
       ("Autowatch Ghost II","a CAN-bus immobiliser with no fob, popular on driveway-parked SUVs."),
       ("Tracker &amp; immobiliser package","the specification most SW13 insurers ask for on a modern keyless car."),
       ("Front and rear dash camera","Castelnau and Church Road are busier than they look at school times.")],
 outro="We fit throughout SW13 - Castelnau, Church Road, Barnes High Street, Mill Hill Road, Nassau Road, Westmoreland Road and the streets around the Common and Barnes Green - and issue certification on the day.",
 h2="Fitting a tracker in Barnes: what is different here",
 p1="Barnes is a driveway area, and driveway areas have one dominant theft method. Relay attacks read the key signal through a wall and repeat it at the car, and a keyless SUV parked a few metres from a front door is the textbook case. It is the reason our Barnes recommendations lean towards an immobiliser as much as a tracker: the tracker is what your insurer certifies and what gets the car back, but the immobiliser is what means it never leaves. We will always be straight with you about which is doing what.",
 p2="Access here is easy by our standards. Most SW13 fittings happen on a private drive with the van alongside, no permit and no restriction hours to work around. The one local factor is the bridges - Hammersmith Bridge's closure to motor traffic has changed how everything moves in and out of Barnes, and the Putney and Chiswick approaches carry the load. It affects our arrival time rather than the work, but it is why we give a window rather than a to-the-minute slot in SW13.",
 where=["Driveways and hardstandings on Castelnau, Nassau Road and Westmoreland Road",
        "Garages on the larger Church Road and Mill Hill Road houses",
        "Kerbside around Barnes Green and the High Street, where drives are not available",
        "Barnes and Mortlake business parking, by arrangement"],
 p3="Keep the keys away from the front wall and in a signal-blocking pouch. It is free, it makes a relay attack harder, and it complements rather than replaces what we fit.",
 faqs=[("What is the actual risk to a car on a Barnes driveway?",
        "Keyless relay theft. The attack reads your key's signal through the wall of the house and repeats it at the car. A tracker recovers the car afterwards; an immobiliser means it does not go. On a driveway in SW13 we would fit both."),
       ("Does the Hammersmith Bridge closure affect you getting here?",
        "It affects our arrival rather than the work - traffic in and out of Barnes now leans on the Putney and Chiswick approaches. It is why we give an arrival window in SW13 rather than a precise time."),
       ("Do you cover Barnes Common and the High Street end?",
        "Yes, all of SW13 - Castelnau, Church Road, Barnes High Street, Mill Hill Road and the streets around the Common and Barnes Green.")]),

"chiswick": dict(
 pc="W4",
 intro="Chiswick runs from the Bedford Park Arts and Crafts houses down to Chiswick Mall on the river, with Turnham Green Terrace in the middle. Most of it has off-street parking of some kind, and the A4 and Great West Road put the whole area within easy reach of the motorway network - which is part of why W4 cars are worth protecting properly.",
 recs=[("Meta Trak S5 Deadlock","tracking plus deadlock immobilisation on a driveway-parked keyless car."),
       ("Autowatch Ghost II","no fob and no visible module, fitted to the CAN bus."),
       ("Tracker &amp; immobiliser package","the specification W4 insurers most often ask for."),
       ("Front and rear dash camera with parking mode","Chiswick High Road and the A4 slip roads generate a lot of low-speed contact.")],
 outro="We fit across W4 - Bedford Park, Chiswick High Road, Turnham Green Terrace, Grove Park, Chiswick Mall, Devonshire Road and the streets down to the river - with certification issued on the day.",
 h2="Fitting a tracker in Chiswick: what is different here",
 p1="Chiswick's proximity to the A4, the M4 and the Chiswick roundabout matters more than it sounds. A car stolen here can be on a motorway within minutes, which is exactly the scenario a Thatcham-approved tracker with a monitored recovery service is built for - and it is a reasonable argument for the S5 rather than the self-monitored S7 if you are weighing the two. We will talk you through the difference honestly rather than simply selling up.",
 p2="The fittings themselves are among the more straightforward ones we do. Bedford Park and Grove Park houses generally have a driveway or a garage, so there is no permit and we work out of the traffic. Chiswick Mall and the streets right by the river are the exception - narrow, often busy with people walking, and prone to Thames flooding on a high spring tide. If you are on the Mall, we will pick a slot around the tide table rather than risk parking a van in it.",
 where=["Driveways and garages in Bedford Park, Grove Park and Sutton Court",
        "Permit and kerbside parking on Devonshire Road and around Turnham Green Terrace",
        "Chiswick Mall and the riverside streets, tide permitting",
        "Chiswick Park and Power Road business parking, by arrangement"],
 p3="If you commute out on the M4 or the A4 daily, mention it - a tracker's recovery performance matters most on the roads a car is actually likely to be taken along, and it shapes which system we recommend.",
 faqs=[("Does being close to the A4 and M4 change what I should fit?",
        "It is a fair argument for a monitored system. A car taken from W4 can be on a motorway in minutes, which is what a Thatcham-approved tracker with a monitored recovery service is designed for. We will explain the S5 and S7 difference rather than just selling up."),
       ("I am on Chiswick Mall - can you fit there?",
        "Yes, but we book around the tide table. The Mall floods on a high spring tide and we would rather not park a van in it. It is a narrow, busy street, so morning slots work best."),
       ("Do you cover Bedford Park and Grove Park?",
        "Yes, along with the rest of W4. Those are among our easier fittings - most houses have a driveway or garage, so no permit and no restriction hours.")]),

"ealing": dict(
 pc="W5, W13",
 intro="Ealing is properly suburban - Hanger Hill, Ealing Common, Montpelier Road and Pitshanger Lane are streets of detached and semi-detached houses with drives and garages. The cars are family SUVs, German saloons and a fair number of modern Range Rovers, and virtually all of them are parked off the public highway. That makes the immobiliser the important half of the conversation.",
 recs=[("Autowatch Ghost II","stops a relayed key signal turning into a stolen car off your own drive."),
       ("Meta Trak S5 Deadlock","tracking and deadlock immobilisation in one insurance-approved system."),
       ("Tracker &amp; immobiliser package","the combination most W5 and W13 policies now specify."),
       ("Front and rear dash camera","drives that open onto through-roads benefit from parking mode.")],
 outro="We fit throughout Ealing - Ealing Common, Hanger Hill, Montpelier Road, Pitshanger Lane, Castlebar, Ealing Broadway and the West Ealing streets - and hand over certification the same day.",
 h2="Fitting a tracker in Ealing: what is different here",
 p1="Ealing's drives and garages mean we almost never deal with a permit, and it also means the honest recommendation here is weighted towards immobilisation. A keyless Range Rover, X5 or Q7 on a suburban drive is the classic relay-theft target: the key is inside the house, close enough to a wall for its signal to be read and repeated, and the car is a few metres away with nothing between it and the road. A tracker recovers the car. An immobiliser stops it moving. On a W5 drive you want both, and if you can only do one, we will tell you which.",
 p2="The practical side is easy. Garage fittings are the best conditions we work in - dry, private, well lit and unhurried, and we can route the loom properly rather than quickly. Drive fittings are nearly as good. Ealing is also far enough out that we tend to schedule it as a half-day route, so if there is a neighbour or a second car at the address, doing them together on one visit saves everyone money.",
 where=["Drives and garages around Hanger Hill, Ealing Common and Castlebar",
        "Pitshanger Lane and the Brentham Garden Estate streets",
        "Montpelier Road and the Mount Park Road area",
        "Ealing Broadway and West Ealing offices, by arrangement"],
 p3="Ealing has a lot of integral garages that have become storage rather than parking. If yours has, no problem - the drive is perfectly workable, and we would rather fit properly outside than badly in a cramped garage.",
 faqs=[("My car is on a suburban drive in Ealing. Is a tracker enough?",
        "It is what your insurer certifies, but on a drive the immobiliser does the harder work. Relay theft reads your key through the wall and repeats it at the car - an immobiliser means it goes no further. On a W5 drive we would fit both, and if you can only do one we will say which."),
       ("Is a garage fitting better than a drive?",
        "Marginally - dry, private and unhurried, so we can route the wiring exactly where it should go. But a drive is perfectly good, and we would rather work well outside than badly in a cramped garage."),
       ("Can you do two cars, or a neighbour's as well?",
        "Yes. We schedule Ealing as a half-day route, so combining vehicles at the same address or next door on one visit saves everyone money.")]),

"kew": dict(
 pc="TW9",
 intro="Kew is a conservation area of Victorian and Edwardian terraces around Kew Green and Kew Gardens Road, with the Gardens on one side and the river on the other. Off-street parking exists but is not universal, and the streets are narrow and permit-controlled. It is a quieter area than most we cover, and the fittings reflect that - but the cars are no less worth protecting.",
 recs=[("Meta Trak S5 with ADR tags","for a car kept on a permit bay in one of the terrace streets."),
       ("Meta Trak S5 Deadlock","where the car is on a drive and relay theft is the concern."),
       ("Tracker &amp; immobiliser package","the specification most TW9 insurers ask for."),
       ("Dash camera with parking mode","narrow terrace streets and a lot of visitor traffic near the Gardens.")],
 outro="We fit across TW9 - Kew Green, Kew Gardens Road, Mortlake Road, Sandycombe Road, North Road, Leyborne Park and the streets around Kew Bridge - with certification handed over on the day.",
 h2="Fitting a tracker in Kew: what is different here",
 p1="Kew's streets are narrow and the parking is controlled, which means a morning slot and either a visitor permit from you or a single yellow outside the loading restriction. The conservation area status has one genuine practical consequence for us: a lot of Kew houses have a front garden rather than a hardstanding, because dropping a kerb here is harder than in most boroughs. So more Kew cars sit on the street than the housing stock would suggest.",
 p2="The other Kew factor is visitor traffic. The Gardens and the river pull people in at weekends and through the summer, and the streets closest to the Green and the main gate fill accordingly. We would rather come on a weekday morning. Kew Bridge and the Mortlake Road approach are the routes in, and both can be slow, so we give an arrival window rather than a precise time and we will call you when we are close.",
 where=["Permit bays on Sandycombe Road, North Road and Leyborne Park",
        "Kew Green and the streets nearest the main gate, weekday mornings",
        "The drives and hardstandings that do exist, on Mortlake Road and Kew Gardens Road",
        "Kew Retail Park and local business parking, by arrangement"],
 p3="If you have off-street space at the back reached from a side lane, tell us - it is not obvious from the front and it makes for a much better fitting.",
 faqs=[("Most Kew houses do not have a driveway. Can you fit on the street?",
        "Yes, that is the majority of our TW9 work. Dropping a kerb is difficult in a conservation area, so more Kew cars sit on the street than you would expect. We need a visitor permit from you or a single yellow outside the loading restriction, and a morning slot."),
       ("Are weekends harder in Kew?",
        "Yes - the Gardens and the river bring visitor traffic and the streets near the Green and the main gate fill up. A weekday morning is a much easier fitting for both of us."),
       ("How precise is the arrival time?",
        "We give a window rather than a time in TW9. Kew Bridge and the Mortlake Road approach can both be slow, and we would rather be honest than late. We call when we are close.")]),

"richmond": dict(
 pc="TW9, TW10",
 intro="Richmond covers a lot of ground and several kinds of parking: the Green and the town centre with its controlled bays, the hill running up towards the Park with garages and private drives, and the riverside and Petersham Road houses. Add the Park itself and the Thames, and you have an area where access varies street by street more than almost anywhere else we work.",
 recs=[("Meta Trak S5 with ADR tags","for a car on a town-centre or Green-side permit bay."),
       ("Meta Trak S5 Deadlock","for the hill and Petersham drives, where relay theft is the concern."),
       ("Tracker &amp; immobiliser package","the specification most Richmond insurers ask for above &pound;75,000."),
       ("Front and rear dash camera","the town centre is tight and the riverside is busy with pedestrians.")],
 outro="We fit throughout Richmond - Richmond Green, Richmond Hill, Petersham Road, Sheen Road, Kew Road, the Vineyard and the riverside streets - and issue certification on the day.",
 h2="Fitting a tracker in Richmond: what is different here",
 p1="Which half of Richmond you are in changes the job. In the town centre and around the Green, parking is controlled, the streets are tight and we work from a permit or a loading window in the morning. Up the hill and out towards Petersham, houses have drives and garages, there is no permit involved, and the fitting is unhurried. Both are routine for us - we just need to know which when you book, because they are scheduled differently.",
 p2="Richmond's floodplain is a genuine consideration on the riverside streets. The Thames comes over the wall at Water Lane and along the towpath on a high spring tide, several times a year, and we will not park a van in it. If you are on the riverside we check the tide table and pick a slot around it. Richmond Park's gate closures and the summer traffic on the A307 affect our arrival more than the work, but they are why we give a window rather than a fixed time.",
 where=["Controlled bays around Richmond Green, the Vineyard and the town centre",
        "Drives and garages up Richmond Hill and out along Petersham Road",
        "Sheen Road and Kew Road, kerbside and off-street",
        "Riverside streets, tide permitting"],
 p3="Richmond Hill is steep and the drives off it are often narrow. If yours is, tell us and we will walk the kit up rather than trying to take the van where it should not go.",
 faqs=[("Richmond varies a lot. What do you need to know when I book?",
        "Whether you are in the controlled town-centre and Green area or up the hill and out towards Petersham with a drive. They are scheduled differently - the first needs a permit and a morning loading window, the second does not."),
       ("Can you fit on the riverside streets?",
        "Yes, but we check the tide table first. The Thames comes over the wall at Water Lane and along the towpath several times a year and we will not park a van in it."),
       ("Do you cover both TW9 and TW10?",
        "Yes - Richmond Green, the town centre, Sheen Road and Kew Road in TW9, and Richmond Hill, Petersham Road and the Park side in TW10.")]),

"richmond-hill": dict(
 pc="TW10",
 intro="Richmond Hill is the stretch running up from the town centre to the Star and Garter and the Park gate, taking in the Terrace, Friars Stile Road and Nightingale Lane. It is steep, narrow and largely permit-controlled, with a mix of period terraces and larger houses with garages. The view is the famous part; for us, the gradient is the operative one.",
 recs=[("Meta Trak S5 with ADR tags","for a car left on a Terrace or Friars Stile Road permit bay."),
       ("Meta Trak S5 Deadlock","where there is a garage or a drive and relay theft is the risk."),
       ("Tracker &amp; immobiliser package","our most-fitted specification on the hill."),
       ("Dash camera with parking mode","the hill is narrow and busy with visitor traffic in summer.")],
 outro="We fit across Richmond Hill and TW10 - the Terrace, Friars Stile Road, Nightingale Lane, Queens Road, Church Road and the streets up to the Park gate - with certification handed over on the day.",
 h2="Fitting a tracker in Richmond Hill: what is different here",
 p1="The gradient is not a trivial detail. Working under a car on a slope needs it chocked properly and the wheels turned, and we would rather spend two minutes doing that than take a chance. Some of the drives off Nightingale Lane and the Terrace are steep enough that we walk the kit up rather than reverse a van down them. None of this affects what we fit or what it costs - it just means we plan the position of the car before we start rather than after.",
 p2="Parking on the hill is controlled and tight, and the Terrace is a genuine visitor destination in summer - the view fills the bays and the pavements from late morning. We book Richmond Hill for the early part of the day for that reason. If you have a garage, that is much the better option: level, private and out of the way of a busy road, and there is no permit to think about.",
 where=["Permit bays on the Terrace, Friars Stile Road and Queens Road",
        "Garages and drives off Nightingale Lane and Church Road",
        "The streets running up to the Star and Garter and the Park gate",
        "Off-street parking on the larger Richmond Hill houses"],
 p3="In winter the hill ices before the flat, and we will reschedule rather than take a van up a steep drive on a bad morning. It is not caution for its own sake - it is your gravel and our van.",
 faqs=[("Does the slope on Richmond Hill cause any problem?",
        "Nothing that stops us - it just means chocking the car properly and turning the wheels before we work under it, and sometimes walking the kit up a steep drive rather than reversing a van down it. It does not change the price or the time."),
       ("Is the Terrace hard to park on?",
        "In summer, yes - the view fills the bays and pavements from late morning. We book Richmond Hill early in the day for that reason. A garage, if you have one, is much easier."),
       ("What happens in icy weather?",
        "We reschedule steep-drive fittings rather than take a van up on a bad morning. It protects your gravel as much as our van.")]),

"putney": dict(
 pc="SW15",
 intro="Putney splits between the mansion blocks along Putney Hill and the Upper Richmond Road, and the family houses of West Putney and the streets up towards Roehampton. The blocks mostly have their own car parks; the houses mostly have drives. Very little of Putney's valuable metal sits on an unrestricted public street overnight, which is a good starting point.",
 recs=[("Meta Trak S5 Deadlock","tracking and deadlock immobilisation for a drive-parked keyless car."),
       ("Meta Trak S7","enough where the car is in a gated block car park."),
       ("Tracker &amp; immobiliser package","the specification most SW15 insurers ask for."),
       ("Front and rear dash camera with parking mode","block car parks are tight and low-speed contact is common.")],
 outro="We fit throughout SW15 - Putney Hill, Upper Richmond Road, West Putney, Putney Heath, Roehampton Lane, Lower Richmond Road and the Putney Bridge streets - and issue certification the same day.",
 h2="Fitting a tracker in Putney: what is different here",
 p1="Mansion-block car parks are the most common Putney setting and among the best places to work: covered, lit, level and out of the traffic. What we need is for the block to admit us. Some of the Putney Hill and Upper Richmond Road blocks require the managing agent to be notified before a contractor comes, and the porter may want to see our insurance - we can send that across in advance. Tell us the block when you book and we will sort the access rather than discovering it on the doorstep.",
 p2="On the West Putney and Roehampton side it is drives and garages, which means no permit and a straightforward job, and it shifts the recommendation towards immobilisation. A keyless car on a drive is a relay-theft target, and an immobiliser is the part that stops the car leaving. Putney Bridge and the Lower Richmond Road are the routes in and both get heavy at peak - we give an arrival window in SW15 rather than a fixed time, and we call when we are close.",
 where=["Mansion-block car parks along Putney Hill and the Upper Richmond Road",
        "Drives and garages in West Putney and up towards Putney Heath",
        "Roehampton Lane and the Roehampton estates",
        "Lower Richmond Road and the streets by the river"],
 p3="If your block's car park has a height restriction, mention it - several of the older SW15 blocks are under two metres and we will bring the kit down in cases rather than turn up in a van that will not fit.",
 faqs=[("Can you fit in my block's car park?",
        "Yes, and it is the best setting we get - covered, lit and level. Some Putney Hill and Upper Richmond Road blocks want the managing agent notified first and the porter may ask for our insurance. Tell us the block when you book and we will arrange it."),
       ("Are the older block car parks too low for your van?",
        "Several SW15 car parks are under two metres. If yours is, we bring the kit down in cases and work on foot - just mention it when you book."),
       ("How precise is the arrival time in Putney?",
        "We give a window. Putney Bridge and the Lower Richmond Road get heavy at peak and we would rather be honest than late. We call when we are close.")]),

"wimbledon": dict(
 pc="SW19",
 intro="Wimbledon Village and the roads around the Common - Parkside, Camp Road, Church Road, Calonne Road - are large houses with long drives, gated developments and garages. It is one of the highest-value areas we cover outside central London, and almost all of the parking is private. The security question here is squarely about whether the car can be driven off the drive.",
 recs=[("Autowatch Ghost II","no fob, no visible module, and a relayed key gets no further than the door."),
       ("Meta Trak S5 Deadlock","insurance-approved tracking with deadlock immobilisation."),
       ("Tracker &amp; immobiliser package","the specification SW19 insurers ask for on the values kept here."),
       ("Dash camera with parking mode","long drives opening onto Parkside and Church Road benefit from a gate-line view.")],
 outro="We fit across SW19 - Wimbledon Village, Parkside, Camp Road, Church Road, Calonne Road, Ridgway, Southside Common and the Wimbledon Park streets - with certification handed over on the day.",
 h2="Fitting a tracker in Wimbledon: what is different here",
 p1="Private drives and gated developments dominate SW19, and the theft method that matters against them is relay attack. The signal from a key inside the house is read and repeated at the car, the car unlocks and starts, and it is gone. Nothing about a gate or a long drive prevents that. What does prevent it is an immobiliser: a Ghost II or a Meta Trak S5 Deadlock means the thief gets into the car and no further. In Wimbledon we recommend the immobiliser as firmly as the tracker, and we will explain exactly which risk each one addresses.",
 p2="The Championships change the area for a fortnight. Late June and early July bring road closures, parking suspensions and residents-only restrictions across the Village and the streets around Church Road, and getting a van in and parked beside a car becomes genuinely difficult. We do fit during the tournament, but we plan around it and we will be honest if a different week would be easier. Outside those two weeks, Wimbledon is among the more relaxed fittings we do.",
 where=["Long drives and garages on Parkside, Camp Road and Calonne Road",
        "Gated developments off Church Road and the Ridgway",
        "Wimbledon Village kerbside and permit parking",
        "Wimbledon Park and the streets down towards the station"],
 p3="A lot of SW19 households keep two or three cars at the address. Fitting them on one visit is meaningfully cheaper than separate appointments - tell us everything on the drive when you book.",
 faqs=[("My car is behind a gate on a long drive. Do I still need an immobiliser?",
        "Yes, and arguably more than the tracker. Relay theft reads your key's signal from inside the house and repeats it at the car - a gate and a long drive do not stop that. A Ghost II or an S5 Deadlock means the car does not move."),
       ("Can you fit during the Championships?",
        "We can, but we plan around it. Late June and early July bring closures, suspended bays and residents-only restrictions around the Village and Church Road. If another week is easier we will tell you."),
       ("Can you do more than one car at the address?",
        "Yes, and it is noticeably cheaper than separate visits. A lot of SW19 households have two or three - list them all when you book.")]),

"cobham": dict(
 pc="KT11",
 intro="Cobham means the private estates - Fairmile, the roads off Oxshott Road and Icklingham Road, and the gated developments running towards Stoke d'Abernon. Long gravel drives, electric gates, multiple cars per household and values well into six figures. It is the heart of the Surrey stockbroker belt and one of the areas where we do the most immobiliser work.",
 recs=[("Autowatch Ghost II","the immobiliser we fit most in KT11 - no fob, nothing visible, and relay-proof."),
       ("Meta Trak S5 Deadlock","insurance-approved tracking with deadlock immobilisation in one system."),
       ("Tracker &amp; immobiliser package","effectively the standard specification for Cobham values."),
       ("Multi-car fitting","most households here have two or more; doing them together costs less.")],
 outro="We fit throughout Cobham and KT11 - Fairmile Lane, Icklingham Road, Oxshott Road, Between Streets, Portsmouth Road, Stoke d'Abernon and the private estates - and issue certification on the day.",
 h2="Fitting a tracker in Cobham: what is different here",
 p1="Cobham has the highest concentration of high-value keyless SUVs of anywhere we cover, and gated private estates do less to protect them than owners expect. A relay attack works from the drive, through the wall of the house, in under a minute, and an electric gate is not an obstacle to a car being driven at it. Nearly every Cobham job we do includes an immobiliser for that reason. If you are weighing a tracker alone against a tracker and immobiliser, the honest answer in KT11 is the latter.",
 p2="The practical side is the easiest we get. Long drives mean we park beside the car, work unhurried, and never think about a permit. What we do need is gate access - a code, a fob or someone at home to let us in - and an accurate idea of how far the drive runs, because on some of the Fairmile properties the car is a long way from anywhere we can put a van. Tell us both when you book. We schedule Surrey as half-day routes, so multi-car households get better value than one car at a time.",
 where=["Private estate drives off Fairmile Lane, Icklingham Road and Oxshott Road",
        "Gated developments towards Stoke d'Abernon and the Portsmouth Road",
        "Garages and car barns on the larger KT11 properties",
        "Cobham village and Between Streets, where drives are shorter"],
 p3="If you keep a car at a second property - a lot of Cobham households have a London flat too - we can fit at either address, and it is often easier to do both cars in one place.",
 faqs=[("The estate is gated. Is that not enough security?",
        "Not against the method that is actually used. Relay theft works from your drive, through the wall of the house, in under a minute, and an electric gate does not stop a car being driven at it. Almost every Cobham fitting we do includes an immobiliser."),
       ("What do you need to get to my car?",
        "Gate access - a code, a fob or someone at home - and a rough idea of how far the drive runs. On some Fairmile properties the car sits a long way from anywhere we can park a van, and it is better to know in advance."),
       ("We have three cars. Is that cheaper together?",
        "Yes, meaningfully. We run Surrey as half-day routes, so doing the household together costs less than three separate visits.")]),

"esher": dict(
 pc="KT10",
 intro="Esher runs from the High Street out to Claremont, Sandown and the private roads towards Oxshott. Large detached houses, gated frontages, in-and-out drives and a car mix that leans heavily on modern keyless SUVs and performance saloons. Almost nothing here is parked on a public street overnight, which puts the emphasis firmly on immobilisation.",
 recs=[("Autowatch Ghost II","CAN-bus immobilisation with no fob and nothing to find."),
       ("Meta Trak S5 Deadlock","tracking with deadlock immobilisation, insurance-approved."),
       ("Tracker &amp; immobiliser package","the specification KT10 insurers ask for at these values."),
       ("Dash camera with parking mode","in-and-out drives onto the Portsmouth Road and Esher High Street.")],
 outro="We fit across Esher and KT10 - Esher High Street, Claremont Lane, Sandown, Portsmouth Road, More Lane, Lower Green and the private roads towards Oxshott - with certification handed over the same day.",
 h2="Fitting a tracker in Esher: what is different here",
 p1="The Esher pattern is a keyless SUV on a private drive within relay range of a hallway key hook, and it is the single most stolen configuration in the country. A gate, a wall and a long drive do not address it; an immobiliser does. So while the tracker is what your insurer certifies and what recovers the car afterwards, the part that stops the car leaving is the immobiliser, and in KT10 we recommend both as a matter of course rather than as an upsell.",
 p2="Access is straightforward - drives and garages, no permits, no restriction hours - but we do need gate codes or someone at home, and it is worth telling us if the drive is gravel and long. Esher sits well for us as part of a Surrey route with Cobham, Weybridge and Oxshott, which is why we can usually offer a KT10 slot within the week. Sandown race days change the traffic on the Portsmouth Road and the High Street; mention it if your fitting falls on one.",
 where=["Private drives and gated frontages off Claremont Lane and More Lane",
        "The roads running towards Oxshott and Fairmile",
        "Garages and car barns on the larger KT10 houses",
        "Esher High Street and Lower Green, where drives are shorter"],
 p3="If a car has been sitting through the winter - and plenty of the second cars here have - we will check the battery before we hard-wire anything and tell you honestly if a conditioner should come first.",
 faqs=[("Gates, a wall and a long drive - do I really need an immobiliser?",
        "Yes. A keyless SUV on a private drive within relay range of a hallway key hook is the most stolen configuration in the country, and none of those physical features address it. The tracker recovers the car; the immobiliser stops it leaving."),
       ("What access do you need in Esher?",
        "A gate code or someone at home, and a heads-up if the drive is long and gravelled so we know where the van can go. No permits are involved in KT10."),
       ("How soon can you come to Esher?",
        "Usually within the week. Esher runs as part of a Surrey route with Cobham, Weybridge and Oxshott, so there are regular slots. Sandown race days affect the traffic - mention it if yours falls on one.")]),

"weybridge": dict(
 pc="KT13",
 intro="Weybridge is St George's Hill, Oatlands and the Brooklands side, and the parking is almost entirely private: gated estate roads, security barriers, long drives and garaging for several cars. St George's Hill in particular has its own estate security, which is genuine protection against a lot of things - but not against the relay attack that takes most cars of this kind.",
 recs=[("Autowatch Ghost II","the immobiliser we fit most on the Hill - no fob, no module to find."),
       ("Meta Trak S5 Deadlock","approved tracking and deadlock immobilisation in one system."),
       ("Tracker &amp; immobiliser package","the standard specification for KT13 values."),
       ("Multi-car fitting","most Weybridge households have several cars; one visit covers them all.")],
 outro="We fit throughout Weybridge and KT13 - St George's Hill, Oatlands Park, Oatlands Drive, Queens Road, Brooklands, Monument Hill and the private estate roads - and issue certification on the day.",
 h2="Fitting a tracker in Weybridge: what is different here",
 p1="St George's Hill has gates and patrols, and it works: it deters opportunists and it makes the estate a poor target for anything that involves loitering. What it does not stop is a relay attack, which needs less than a minute on your own drive and produces a car that drives itself out through the gate under its own power. That is the gap an immobiliser fills, and it is why the Hill and Oatlands are two of the places we fit the Ghost II most often.",
 p2="Getting to you needs a little planning. St George's Hill requires us to be authorised at the gate - residents normally call it in, and the gatehouse will want the vehicle and the name. Oatlands and the Brooklands side are more open but still mostly gated at the property. Tell us the estate and the gate arrangement when you book. Weybridge sits on the same Surrey route as Cobham and Esher, so slots come up regularly and multi-car households save by doing everything at once.",
 where=["St George's Hill estate roads, with gatehouse authorisation",
        "Oatlands Park, Oatlands Drive and Monument Hill drives",
        "Brooklands and the Queens Road side",
        "Garaging and car barns on the larger KT13 properties"],
 p3="If your cars are split between a garage and a drive, we will do them in whichever order keeps the doors closed longest - it matters more than it sounds on a wet day.",
 faqs=[("St George's Hill has gates and patrols. Is that not enough?",
        "It is real protection against opportunists, but not against relay theft - that takes under a minute on your own drive and the car drives out through the gate under its own power. An immobiliser is what closes that gap, and the Hill is where we fit the Ghost II most."),
       ("How do you get through the gate?",
        "Residents normally call it in - the gatehouse will want our vehicle and name. Tell us the estate and the gate arrangement when you book and we will make sure it is cleared before we set off."),
       ("Can you do several cars in one visit?",
        "Yes, and most Weybridge households do. It is cheaper than separate appointments and we plan the order around keeping garage doors closed in bad weather.")]),

"ascot": dict(
 pc="SL5",
 intro="Ascot, Sunningdale and Sunninghill are large properties in big grounds - gated entrances, gravel drives measured in tens of metres, garaging and car barns, and a car mix that runs from modern keyless SUVs to weekend classics. It is a long way from a London permit bay, and the considerations are correspondingly different.",
 recs=[("Autowatch Ghost II","CAN-bus immobilisation with nothing visible and no fob to lose."),
       ("Meta Trak S5 Deadlock","insurance-approved tracking with deadlock immobilisation."),
       ("Tracker &amp; immobiliser package","the specification we fit most across SL5."),
       ("Battery health check","classics and weekend cars need one before anything is hard-wired.")],
 outro="We fit across Ascot and SL5 - Ascot High Street, Sunninghill, Sunningdale, Coworth, Winkfield, Cheapside and the private roads towards Windsor Great Park - with certification handed over the same day.",
 h2="Fitting a tracker in Ascot: what is different here",
 p1="Two kinds of car sit in Ascot garages, and they need different conversations. The modern keyless SUV needs an immobiliser, because a relay attack works just as well at the end of a two-hundred-metre gravel drive as it does on a Fulham street. The weekend or classic car needs a battery conversation first: a hard-wired tracker draws a small standing current, and on a car that does five hundred miles a year that is the difference between turning the key and calling a recovery truck. We check and advise rather than just fitting.",
 p2="Access here is about distance rather than restriction. There are no permits, but the car is often a long way from any road, sometimes behind two sets of gates, and occasionally in a barn with no power. We bring our own lighting and work off our own supply, so that is fine - we just need to know in advance. Race week at Ascot changes the roads around the course substantially for several days in June, and we will schedule around it if your fitting falls in it.",
 where=["Gated drives and grounds around Sunninghill, Sunningdale and Coworth",
        "Garaging and car barns on the larger SL5 estates",
        "Winkfield, Cheapside and the roads towards Windsor Great Park",
        "Ascot High Street and the village properties"],
 p3="Where a property has several cars in a barn, we will usually suggest doing the ones in daily use first and the occasional-use cars second, so the battery advice can be given with the car in front of us.",
 faqs=[("I have a weekend classic as well as the daily car. Any difference?",
        "Yes. A hard-wired tracker draws a small standing current, which matters on a car doing a few hundred miles a year - it can be the difference between starting and a recovery truck. We check battery health and advise before we fit, rather than fitting and hoping."),
       ("The car is at the end of a very long drive, in a barn with no power. Is that a problem?",
        "No. We bring our own lighting and work off our own supply. We just need to know in advance so we arrive equipped and know where the van can go."),
       ("Does race week affect getting to Ascot?",
        "Substantially, for several days in June - the roads around the course change and it gets slow. We will schedule around it if your fitting falls in that week.")]),

"virginia-water": dict(
 pc="GU25",
 intro="Virginia Water is largely the Wentworth Estate: private roads, security patrols, gated drives set well back from the road, and some of the highest vehicle values in Surrey. The estate handles a great deal of the physical security. What it cannot address is the electronic attack that takes most modern cars, which is the specific gap we are asked to close here.",
 recs=[("Autowatch Ghost II","no fob, no visible module, and a relayed key gets nowhere."),
       ("Meta Trak S5 Deadlock","insurance-approved tracking with deadlock immobilisation."),
       ("Tracker &amp; immobiliser package","the specification GU25 values effectively require."),
       ("Multi-car fitting","Wentworth households commonly have three or more cars.")],
 outro="We fit throughout Virginia Water and GU25 - the Wentworth Estate, Christchurch Road, Wellington Avenue, Callow Hill, Blacknest and the private roads towards Windsor Great Park - and issue certification on the day.",
 h2="Fitting a tracker in Virginia Water: what is different here",
 p1="Wentworth's private roads and patrols make the estate a hard place to steal a car the old-fashioned way, and that is precisely why the electronic route is what gets used. A relay attack is quiet, takes under a minute, needs no tools and no forced entry, and produces a car that drives out past the patrol under its own power looking entirely legitimate. An immobiliser is the countermeasure that actually addresses it, and it is the majority of what we fit in GU25.",
 p2="Access needs organising rather than negotiating. The estate roads are private, drives are long and gated, and the car is often not visible from the road at all. Residents normally clear us in advance and give us a gate code or a name at the entrance. Tell us the arrangement when you book. Virginia Water sits at the far end of our Surrey route, so we schedule it as part of a half-day - which makes it a good area to do two or three cars at once rather than one at a time.",
 where=["Wentworth Estate private roads and gated drives",
        "Christchurch Road, Wellington Avenue and Callow Hill",
        "Garaging and car barns on the larger GU25 properties",
        "Blacknest and the roads towards Windsor Great Park and Sunningdale"],
 p3="If a car is stored under a cover or on a battery conditioner, leave it as it is - we would rather see the setup as it normally lives and give you advice that fits it.",
 faqs=[("Wentworth has private roads and patrols. Why would I need an immobiliser?",
        "Because those measures make the old-fashioned methods hard, which is exactly why the electronic one gets used. A relay attack is silent, takes under a minute, needs no tools, and the car drives out past the patrol under its own power. An immobiliser is what stops it."),
       ("How do you get onto the estate?",
        "Residents clear us in advance and give us a gate code or a name at the entrance. Tell us the arrangement when you book - the roads are private and the car is often not visible from the road at all."),
       ("We have several cars. Best way to do it?",
        "All at once. Virginia Water is at the far end of our Surrey route so we schedule it as a half-day, which makes two or three cars in one visit considerably better value.")]),
}
