# -*- coding: utf-8 -*-
"""Per-marque copy for the <make>-tracker-installation pages.

The 12 make pages were 80-85% phrase-identical to each other. Each entry below
supplies marque-specific content: which models are actually targeted, how the
theft methods apply to that marque, what the installation involves on that
platform, and what owners of that marque tend to ask.

Deliberately hedged where the public evidence is model-specific: CAN injection
was first documented publicly on a Toyota RAV4, and we describe the technique
without asserting which other models have been proven vulnerable.
"""

MAKES = {
"range-rover": dict(
 name="Range Rover",
 models="Range Rover (L405 and L460), Range Rover Sport, Velar, Evoque and Discovery",
 intro="No vehicle in Britain has been targeted harder than the Range Rover. For several years the theft rate was severe enough that mainstream insurers withdrew cover for some models in London postcodes altogether, and specialist policies were written on the condition that an approved tracker and an immobiliser were both fitted. Land Rover has since moved to ultra-wideband keys on newer cars, but the L405 generation and the Sports and Velars alongside it remain the most stolen vehicles we are asked to protect.",
 threat="Two methods matter on a Range Rover. Relay attack copies the signal from a key inside the house and repeats it at the car - it takes under a minute and needs nothing more than two people and a pair of handheld units. The second, CAN injection, bypasses the key entirely by reaching the vehicle network through an accessible harness and instructing the car to unlock and start. It was first documented publicly on a different marque, but the technique is generic to CAN-based vehicles and it is the reason a tracker alone is no longer a sufficient answer on a car of this kind.",
 fitting="On the L405 and L460 there is genuinely discreet routing available, and we use it - the unit does not go where a thief expects to find it, and we will not tell you on a public web page where that is. The vehicle's own systems stay untouched: we take a switched and a permanent feed from factory points, use the manufacturer's connector standards, and there is no cutting or splicing into the loom. Air suspension needs the car left in the right mode while we work, which is one reason we prefer a drive or a garage over a kerbside bay for these.",
 rec=[("Meta Trak S5 Deadlock","tracking plus deadlock immobilisation - the specification most insurers now require on a London-registered Range Rover."),
      ("Autowatch Ghost II","CAN-bus immobilisation with no fob and no visible module, so a relayed or injected signal gets no further than the doors."),
      ("Tracker &amp; immobiliser package","the combination that keeps prestige policies in place; we issue certification on the day."),
      ("Signal-blocking pouch and key discipline","free, and it makes the relay half of the problem materially harder before we fit anything.")],
 faqs=[("Will my insurer accept a tracker on its own for a Range Rover?",
        "Increasingly not. On a London-registered Range Rover most specialist insurers now ask for an approved tracker and an immobiliser together, and some will not quote at all without both. We confirm exactly what your policy requires at the assessment, before anything is booked."),
       ("My Range Rover has the newer ultra-wideband key. Am I safe?",
        "Ultra-wideband keys make the classic relay attack much harder, and that is real progress. It does not address attacks that bypass the key altogether by reaching the vehicle network directly, and it does not change what your insurer asks for. An immobiliser is still the part that stops the car being driven."),
       ("Does fitting affect the air suspension or the warranty?",
        "No. We take factory feeds using manufacturer connector standards with no cutting or splicing, and the car is left in the correct mode while we work. Installation is to manufacturer standard and your warranty is unaffected.")]),

"defender": dict(
 name="Land Rover Defender",
 models="new Defender 90, 110 and 130, and the earlier Td5 and Puma Defenders",
 intro="The Defender is stolen for two quite different reasons, and which one applies depends on which Defender you own. The current L663 is taken as a vehicle - keyless, in demand, and straightforward to move. The older Td5 and Puma Defenders are taken for parts, and a stripped chassis is worth enough that thieves will tow one away without ever starting it. That distinction changes the security specification more than anything else about the car.",
 threat="For the L663, relay attack is the method: key signal read through a wall, repeated at the car, driven away in well under a minute. For a classic Defender there may be no keyless system to attack at all, which sounds reassuring until you realise the alternative is a flatbed. A tracker earns its place on an older Defender precisely because the theft does not involve starting the engine, and a tracker with its own power and motion sensing will report a car being lifted when an ignition-triggered system would not.",
 fitting="The new Defender is a modern CAN-bus vehicle and takes a Ghost II or an S5 Deadlock cleanly. Classic Defenders are a different job: simpler electrically, but with far fewer places to hide anything, more exposure to water, and often a battery and charging system that has seen better days. We check the electrical condition before we fit on an older Defender, and we will tell you if the alternator or battery should be dealt with first - a tracker that cannot report because the battery is flat is worse than no tracker at all.",
 rec=[("Meta Trak S5 with ADR tags","for a new Defender used daily and parked on a drive or a farm yard."),
      ("Autowatch Ghost II","for the L663 - no fob, nothing visible, and a relayed signal gets nowhere."),
      ("Self-powered tracking for a classic Defender","reports movement even when the car is being towed rather than driven."),
      ("Electrical health check first","on Td5 and Puma Defenders we look at battery and charging before hard-wiring anything.")],
 faqs=[("My Defender is a 1998 Td5 with no keyless entry. Do I need a tracker?",
        "Arguably more than a newer one. Older Defenders are stolen for parts and frequently towed rather than driven, so there is no ignition event to trigger anything. A tracker with its own power and motion sensing reports the car being lifted, which is exactly the scenario that catches owners out."),
       ("Is a new Defender as vulnerable as a Range Rover?",
        "It is a keyless vehicle on the same broad platform philosophy, so relay attack applies in the same way. It is in high demand and easy to move on. We fit the same combination - approved tracker plus immobiliser - and most insurers ask for it."),
       ("Can you fit at a farm or a yard rather than a house?",
        "Yes, and we do it regularly. We bring our own lighting and work off our own power, so a barn or a yard with no supply is not a problem. We just need to know in advance so we arrive equipped.")]),

"porsche": dict(
 name="Porsche",
 models="911, Cayenne, Macan, Panamera, Taycan, Boxster and Cayman",
 intro="Porsche ownership splits neatly for our purposes. The Cayenne and Macan are used daily, parked on drives, and stolen the way any in-demand keyless SUV is stolen. The 911s, Boxsters and Caymans - especially the air-cooled and early water-cooled cars - are often stored, driven a few thousand miles a year, and carry a value that has nothing to do with their insurance group. Those two situations need different advice, and we give it differently.",
 threat="On a Cayenne, Macan, Panamera or Taycan the risk is relay attack from a drive, and the countermeasure is an immobiliser rather than more tracking. On an older 911 or Boxster the risk is different again: these cars are taken from storage, moved by transporter, and broken for parts that are worth more than the shell. They also frequently have no CAN bus to hang a modern immobiliser on, so the answer is a well-hidden tracker with independent power and motion alerting, not a CAN-based system that has nothing to talk to.",
 fitting="Modern Porsches take a Ghost II cleanly - it sits on the CAN bus, needs no fob, and adds a sequence the car will not start without. On the older cars the work is more considered: a 993 or a 996 has limited routing and a lot of visible trim, and the interior is not something to be casual with. We take our time, we use existing looms and factory grommets, and everything we fit is reversible without a trace. If you also want CarPlay in an older Porsche - a PCCM Plus in a Gen 1 996, 986, 997.1 or 987.1, for instance - we can do both on the same visit so the trim comes out once.",
 rec=[("Autowatch Ghost II","for Cayenne, Macan, Panamera and Taycan - relay-proof, no fob, nothing on show."),
      ("Meta Trak S5 with ADR tags","approved tracking for a daily-driven Porsche parked on a drive or a street."),
      ("Independently powered tracking for stored cars","an air-cooled 911 taken by transporter never turns a key; the tracker has to notice anyway."),
      ("Battery conditioning advice","a car doing a few hundred miles a year needs a healthy battery before anything is hard-wired.")],
 faqs=[("I have an air-cooled 911 in storage. What actually protects it?",
        "A well-hidden tracker with its own power and motion alerting. Cars like yours are taken by transporter and broken for parts, so there is no ignition event and no key involved - a CAN-based immobiliser has nothing to defend against. We would also look at the battery, because a stored car's is usually the weak point."),
       ("Is a Macan or Cayenne at the same risk as a Range Rover?",
        "The method is the same - relay attack from a drive - even if the volumes differ. We fit the same answer: an approved tracker for recovery and certification, and an immobiliser so the car does not move in the first place."),
       ("Can you fit a tracker and PCCM Plus on one visit?",
        "Yes, and it is the sensible way to do it on an older Porsche. The trim comes out once instead of twice, and PCCM Plus fits the Gen 1 cars - 996, 986, 997.1 and 987.1. Gen 2 cars need a different CarPlay route and we will tell you which applies.")]),

"ferrari": dict(
 name="Ferrari",
 models="Roma, 296, SF90, F8, 812, Portofino, California and the modern classics",
 intro="Almost every Ferrari we protect is stored rather than parked. It lives in a garage, a car barn or a specialist facility, it covers low mileage, and it spends most of the year stationary on a conditioner. That single fact changes the security conversation more than the badge does: the threats to a stored car are theft by transporter and theft from within a facility, and the constraint on any hard-wired device is a battery that is already doing very little.",
 threat="A Ferrari is rarely driven away. It is loaded, and the thief does not need the key to do it. Which means an ignition-triggered alert is useless and a well-placed tracker with independent power and motion sensing is the thing that matters - it should raise an alarm when the car tilts onto a ramp, not when someone turns a key that nobody is going to turn. Where a Ferrari is kept in shared or managed storage, the second consideration is who has legitimate access, which is what driver-recognition tags are for.",
 fitting="Two things govern a Ferrari fitting. The first is the battery: a hard-wired tracker draws a small standing current, and on a car doing five hundred miles a year that current is not trivial. We check battery and conditioner setup first and give you an honest answer about whether the installation is safe for how the car is actually used. The second is the interior. Trim and carbon are not to be levered at, and on a mid-engined car the routing options are genuinely limited. We work slowly, use existing looms, and everything is reversible.",
 rec=[("Independently powered tracking with motion alerting","catches a car being loaded, which is how a Ferrari is actually taken."),
      ("Meta Trak S5 with ADR driver tags","for shared or managed storage, where legitimate movement needs distinguishing from theft."),
      ("Battery and conditioner review","before anything is hard-wired into a car that sits for months."),
      ("Autowatch Ghost II","on the modern cars, where the CAN bus supports it and the car is driven regularly.")],
 faqs=[("Will a tracker flatten my Ferrari's battery?",
        "It is the right question to ask, and it is the first thing we check. A hard-wired tracker draws a small standing current, which matters on a car covering a few hundred miles a year. We look at the battery and your conditioner setup and give you a straight answer before we fit - sometimes the honest advice is to sort the charging first."),
       ("The car is loaded onto a transporter, not driven. Does a tracker help?",
        "Only the right kind. An alert tied to the ignition will never fire, because nobody turns a key. What you need is independent power and motion sensing, so the alarm is raised when the car tilts onto a ramp. That is what we fit on stored cars."),
       ("The car is in shared storage. Anything different?",
        "Yes - driver-recognition tags. In a managed facility cars get moved legitimately, and a plain tracker cannot tell an authorised shuffle from a theft. With ADR tags your own movements are silent and anyone else's are not.")]),

"lamborghini": dict(
 name="Lamborghini",
 models="Urus, Huracán, Aventador and Revuelto",
 intro="Lamborghini ownership divides almost perfectly between the Urus and everything else. The Urus is a keyless SUV used daily, parked on drives and in London car parks, and it is stolen the way other high-value SUVs are stolen. The Huracán, Aventador and Revuelto are stored, driven occasionally, conspicuous when they move, and taken - when they are taken - by transporter or from the facility they are kept in. Same badge, two completely different security briefs.",
 threat="For the Urus, relay attack from a drive is the method, and an immobiliser is the countermeasure that actually stops it. For the mid-engined cars the risk is different: they are too recognisable to drive far, so they get loaded. An ignition-triggered alert never fires. Motion sensing with independent power does. There is also a straightforward exposure that has nothing to do with electronics - these cars attract attention, are filmed constantly, and their movements are easy to predict, which is worth thinking about separately from what we fit.",
 fitting="The Urus is a modern CAN-bus vehicle and takes a Ghost II or an S5 Deadlock without complication. On a Huracán or Aventador the constraint is space and access - there is very little room behind the trim, carbon panels are not to be flexed, and the routing paths are few. We plan the position before we start rather than improvising, and we accept that it is a slower job than an SUV. Everything is reversible, and nothing is cut or spliced.",
 rec=[("Autowatch Ghost II","for the Urus - relay-proof CAN-bus immobilisation, no fob, nothing visible."),
      ("Meta Trak S5 Deadlock","approved tracking with deadlock immobilisation on a daily-driven car."),
      ("Independently powered tracking with motion alerting","for the mid-engined cars, which are loaded rather than driven."),
      ("ADR driver tags","where the car lives in managed or shared storage.")],
 faqs=[("Is the Urus at the same risk as any other big SUV?",
        "In terms of method, yes - relay attack from a drive, under a minute, no tools. In terms of desirability it is worse. We fit an approved tracker for certification and recovery and an immobiliser so the car does not move, and in KT and SW postcodes most insurers ask for both."),
       ("My Huracán is stored and barely driven. What is the actual risk?",
        "Being loaded onto a transporter. The car is far too recognisable to drive any distance, so an ignition-linked alert will never fire. Independent power and motion sensing is what raises the alarm when the car tilts onto a ramp."),
       ("Is there room to fit anything in a mid-engined car?",
        "There is, but it is tight and it is a slower job than an SUV. Very little space behind the trim, carbon panels that should not be flexed, and few routing paths. We plan the position before we start, and everything we fit is reversible with no cutting or splicing.")]),

"mclaren": dict(
 name="McLaren",
 models="720S, 750S, Artura, GT, 570S and the Sports Series and Super Series cars",
 intro="A McLaren is built around a carbon fibre monocoque, and that has a direct and unusual consequence for security installation: the routing paths a fitter would normally use on a steel or aluminium car largely do not exist. Add doors that open upwards, a lot of structural carbon that must not be drilled or clamped, and a car that is usually stored rather than parked, and you have the most technically constrained installation we do.",
 threat="McLarens are stored, low-mileage and conspicuous, so they are loaded rather than driven away - a transporter and a winch, with no key involved and no ignition event to trigger anything. That is the scenario the security has to address. The modern cars are also CAN-based and support a proper immobiliser for the times they are on the road, but if you own one McLaren and it lives in a garage, motion-sensed tracking with its own power supply is doing the real work.",
 fitting="The tub is the whole story. Nothing is drilled, nothing is clamped to structure, and we use existing looms and factory routes exclusively - which on a McLaren means fewer options than on almost any other car we work on. It is a slower fitting and we price the time honestly rather than pretending it is the same job as an SUV. Everything is reversible and leaves no trace, which matters more here than most places because these cars are inspected closely at sale.",
 rec=[("Independently powered tracking with motion alerting","the answer for a stored car that is loaded, not driven."),
      ("Autowatch Ghost II","for a McLaren used on the road, where the CAN bus supports it."),
      ("Meta Trak S5 with ADR tags","approved tracking and driver recognition for managed storage."),
      ("Battery and conditioner review","a stored McLaren's battery is the usual limiting factor on any hard-wired device.")],
 faqs=[("Does the carbon tub limit what can be fitted?",
        "It limits where things can go, not what can be fitted. Nothing is drilled and nothing is clamped to structure - we use existing looms and factory routes only, and on a McLaren there are fewer of those than on almost any other car. It is a slower job and we price the time honestly."),
       ("Will an installation show up when I sell the car?",
        "It should not, and that is deliberate. Everything is reversible and leaves no trace - no cut looms, no drilled panels, no adhesive on trim. These cars get inspected closely at sale and we fit accordingly."),
       ("The car is garaged all year. Is a tracker worth it?",
        "Yes, but the right kind. A garaged McLaren is taken by transporter, so an ignition-linked alert never fires. Motion sensing with independent power is what notices the car being moved, and it is the part that matters here.")]),

"bentley": dict(
 name="Bentley",
 models="Bentayga, Continental GT, Flying Spur and Mulsanne",
 intro="Bentley theft in London is overwhelmingly a Bentayga story. It is the model used daily, parked on drives and in residential car parks, and it sits in the same relay-attack category as every other high-value keyless SUV. The Continental GT and Flying Spur are stolen less often and are more likely to be driven regularly and kept off the street, and the Mulsannes we see are generally stored. The specification follows the use, not the badge.",
 threat="For a Bentayga on a drive, relay attack is the method - the key signal read through a wall, repeated at the car, gone in under a minute. Physical measures do not address it: a gate does not stop a car that starts and drives itself out. There is a second consideration specific to Bentleys, which is that they are more likely than most cars to be moved by someone other than the owner - a chauffeur, staff, a valet. A plain tracker cannot tell an authorised movement from a theft, and driver-recognition tags exist precisely for that.",
 fitting="Bentleys are modern CAN-bus vehicles and take a Ghost II or an S5 Deadlock cleanly. The care goes into the interior: veneer, hide and knurled metal are unforgiving, and a trim panel that has been levered rather than released properly is obvious forever. We take factory feeds with manufacturer connector standards, use existing routes, and cut nothing. If your car is under warranty or on a Bentley service plan, the installation does not affect either.",
 rec=[("Autowatch Ghost II","for a Bentayga on a drive - relay-proof, no fob, nothing visible."),
      ("Meta Trak S5 with ADR driver tags","where a chauffeur, staff or a valet also moves the car."),
      ("Tracker &amp; immobiliser package","the specification most insurers ask for at Bentley values, certified on the day."),
      ("Dash camera with parking mode","in-and-out drives and tight residential car parks are where the damage claims start.")],
 faqs=[("Is the Bentayga particularly targeted?",
        "It is the Bentley we are asked about most, and it sits squarely in the high-value keyless SUV category that relay attack was made for. The Continental GT and Flying Spur come up less often. We would fit an approved tracker and an immobiliser to a Bentayga on a drive without hesitation."),
       ("My chauffeur moves the car. What should I fit?",
        "Meta Trak S5 with ADR driver tags. The tag stays on your keyring, so your own movements are silent and a move without it raises an alert. A plain tracker will tell you the car moved but not whether it should have."),
       ("Will this affect my warranty or service plan?",
        "No. We install to manufacturer standard using factory feeds and manufacturer connector standards, and nothing is cut or spliced. Your warranty and service plan are unaffected.")]),

"rolls-royce": dict(
 name="Rolls-Royce",
 models="Cullinan, Ghost, Phantom, Wraith, Dawn and Spectre",
 intro="A Rolls-Royce is more likely than any other car we protect to be driven by someone other than its owner. Chauffeurs, staff, hotel and club valets and estate managers all legitimately move these cars, and that reframes the security question entirely. The theft risk is real - the Cullinan in particular sits in the targeted keyless SUV category - but the more common practical need is knowing which movements were authorised.",
 threat="For the Cullinan, relay attack applies as it does to any keyless SUV: signal read through a wall, repeated at the car, driven away. For the whole range, the subtler exposure is access. A car that is routinely handed to third parties passes through many hands, and a plain tracker reports every movement identically. Driver-recognition tags separate the two, which is why we fit them on Rolls-Royces more often than on any other marque. Where an owner would rather hand over nothing at all, a CAN-bus immobiliser with no fob is the cleaner answer.",
 fitting="These are modern CAN-bus cars and the electronics are straightforward. The interior is not. Lambswool, hide, veneer and the coach doors on a Phantom or a Wraith all demand that panels are released properly rather than persuaded, and a Rolls-Royce interior shows a mistake permanently. We work slowly, use existing looms and factory grommets, take feeds from factory points, and leave nothing that a dealer inspection would find. Starlight headliners are not touched.",
 rec=[("Meta Trak S5 with ADR driver tags","the specification we fit most on this marque, for exactly the access reason above."),
      ("Autowatch Ghost II","where nothing should be handed over at all - no fob, no visible module."),
      ("Tracker &amp; immobiliser package","approved protection at the values involved, with certification on the day."),
      ("Dash camera with parking mode","useful where the car is parked by valets and returned with damage nobody remembers.")],
 faqs=[("Several people drive the car. How do I know which movements are legitimate?",
        "Driver-recognition tags. The ADR tag stays on the keyring of whoever is authorised, so their movements are silent while a move without a tag raises an alert. It is the reason we fit Meta Trak S5 with tags on Rolls-Royces more than on any other marque."),
       ("Will you touch the starlight headliner?",
        "No. It is not on any routing path we use, and we would not go near it. Panels are released properly rather than levered, we use existing looms and factory grommets, and there is nothing left for a dealer inspection to find."),
       ("Is the Cullinan a theft target?",
        "It is a high-value keyless SUV, so yes - relay attack applies in the same way it does to a Bentayga or a Range Rover. We would fit an approved tracker and an immobiliser, and most insurers at this value ask for both.")]),

"aston-martin": dict(
 name="Aston Martin",
 models="DBX, DB11, DB12, Vantage, DBS and the earlier DB9 and V8 Vantage",
 intro="The DBX changed what Aston Martin security means. Before it, most Astons we protected were sports cars that were driven for pleasure and stored the rest of the time - and the risk was theft from storage, by transporter. The DBX is a keyless SUV used daily and parked on drives, which puts it in the most-targeted category in the country. Both kinds of Aston are on our books and they get different advice.",
 threat="A DBX on a drive faces relay attack, and an immobiliser is what stops it. A DB9, V8 Vantage or DB11 in a garage faces being loaded, and independently powered motion-sensed tracking is what notices. The older cars have a further wrinkle: they are frequently stored on a conditioner and driven a few hundred miles a year, so battery draw is a genuine engineering consideration rather than a footnote, and we treat it as one.",
 fitting="The DBX is a straightforward modern CAN-bus installation and takes a Ghost II cleanly. The sports cars need more thought - the earlier DB9 and V8 Vantage are Ford-era electronics in a hand-trimmed interior, with limited routing and trim that does not forgive rough handling. We use factory routes and existing looms, cut nothing, and leave the installation fully reversible. On any car that sits, we check battery health before we hard-wire, and we will say if the charging setup needs attention first.",
 rec=[("Autowatch Ghost II","for a DBX on a drive - relay-proof, no fob, nothing visible."),
      ("Meta Trak S5 Deadlock","approved tracking with deadlock immobilisation for a daily-driven Aston."),
      ("Independently powered tracking with motion alerting","for a stored DB9, Vantage or DBS that would be loaded rather than driven."),
      ("Battery health check","on any Aston covering low annual mileage, before anything is hard-wired.")],
 faqs=[("Is the DBX treated differently from my V8 Vantage?",
        "Completely. The DBX is a keyless SUV on a drive and faces relay attack, so the immobiliser does the important work. A stored Vantage faces being loaded onto a transporter, where no key is involved at all - that needs independently powered motion-sensed tracking instead."),
       ("My DB9 sits on a conditioner most of the year. Will a tracker cope?",
        "It can, but the battery is the constraint and we check it before we fit. A hard-wired tracker draws a small standing current, and on a car doing a few hundred miles a year that is a real consideration. If the charging setup needs attention we will say so rather than fit and hope."),
       ("Will fitting mark the interior?",
        "It should not. Aston interiors are hand-trimmed and unforgiving, so panels are released properly rather than levered, we use factory routes and existing looms, and nothing is cut. The installation is fully reversible.")]),

"bmw": dict(
 name="BMW",
 models="M3, M4, M5, X5, X6, X7, 5 and 7 Series, and the i and iX electric range",
 intro="BMW theft in London concentrates on two groups: the M cars, taken for what they are, and the X5, X6 and X7, taken because a large keyless SUV is easy to move and easy to sell. Owners of both come to us for the same reason - the car sits on a drive or a residential street, the key lives in the house, and the gap between those two facts is where the theft happens.",
 threat="Relay attack is the volume method and it works on any keyless BMW. The more interesting threat is CAN injection, which bypasses the key entirely: the attacker reaches the vehicle network through an accessible point in the harness and instructs the car to unlock and start. The technique was first documented publicly on another marque and is generic to CAN-based vehicles rather than proven model-by-model, but it is the reason we recommend an immobiliser that adds an authorisation step the network itself cannot supply.",
 fitting="BMWs are among the most straightforward cars we work on. The CAN architecture is well understood, a Ghost II integrates cleanly, and the trim releases properly if you know the clips. We take factory feeds using manufacturer connector standards and cut nothing, so warranty and BMW service plans are unaffected. If your car has an iDrive fault or you want CarPlay activated at the same time, we do that work too and it makes sense to combine the visits.",
 rec=[("Autowatch Ghost II","the immobiliser we fit most on BMWs - no fob, no visible module, and it defeats relay attack outright."),
      ("Meta Trak S5 Deadlock","approved tracking with deadlock immobilisation, for insurers who specify both."),
      ("Tracker &amp; immobiliser package","the standard recommendation for an M car or an X-series on a London drive."),
      ("Front and rear dash camera","M cars attract attention parked as well as moving.")],
 faqs=[("Does a Ghost II work properly on a BMW?",
        "Yes - BMW's CAN architecture is well understood and the Ghost integrates cleanly. It is the immobiliser we fit most on this marque: no fob, no visible module, and it adds a start sequence the car will not move without, which is what defeats a relayed key."),
       ("What is CAN injection and should I worry about it?",
        "It bypasses the key entirely - the attacker reaches the vehicle network through an accessible point in the harness and tells the car to unlock and start. It was first documented publicly on another marque and is a generic technique rather than proven model-by-model, but it is the reason we favour an immobiliser that adds an authorisation step the network cannot supply."),
       ("Can you sort an iDrive problem at the same time?",
        "Yes. We do iDrive reboots, coding and CarPlay activation as well as security, and combining them into one visit saves you an appointment and means the trim comes off once.")]),

"mercedes": dict(
 name="Mercedes-Benz",
 models="G-Class, GLE, GLS, S-Class, E-Class and the AMG range",
 intro="The G-Class is the Mercedes we are asked about most, and for good reason - it holds its value, it is in demand everywhere, and it is straightforward to move. Behind it come the GLE and GLS, the S-Class, and the AMG cars. What they have in common is KEYLESS-GO, and what owners often assume is that a modern Mercedes key has already solved relay theft. It has not, and that assumption is worth correcting before it costs you a car.",
 threat="KEYLESS-GO keys have a motion sensor that puts the key to sleep when it has been still for a while, and that genuinely helps - a key on a hall table overnight is harder to relay than it used to be. It does nothing for a key in a coat pocket by the door, or one that has just been put down, and it does nothing about attacks that bypass the key by reaching the vehicle network directly. The honest position is that the key improvements raised the bar and an immobiliser is still what stops the car being driven.",
 fitting="Mercedes CAN architecture takes a Ghost II or an S5 Deadlock cleanly, and on a G-Class there is more room to work with than on almost any other car in this list. We take factory feeds with manufacturer connector standards, use existing looms, and cut nothing, so warranty and service plans are unaffected. On AMG models with the performance seats and the lower trim, access is tighter and it is a slower job - we would rather take the extra hour than force a panel.",
 rec=[("Autowatch Ghost II","for a G-Class, GLE or AMG on a drive - relay-proof, no fob, nothing visible."),
      ("Meta Trak S5 Deadlock","approved tracking with deadlock immobilisation, which many insurers now specify."),
      ("Tracker &amp; immobiliser package","the combination we fit most on the G-Class, certified on the day."),
      ("Signal-blocking pouch","free and effective - KEYLESS-GO's motion sensor does not cover a key in a coat by the door.")],
 faqs=[("Doesn't my KEYLESS-GO key already stop relay theft?",
        "Partly. The key has a motion sensor that puts it to sleep when it has been still for a while, which genuinely helps overnight. It does nothing for a key in a coat pocket by the door, or one just put down, and nothing for attacks that bypass the key entirely. It raised the bar; an immobiliser is what stops the car moving."),
       ("Is the G-Class really that targeted?",
        "It is the Mercedes we are asked about most. It holds value, it is in demand internationally, and it is easy to move on. On a drive in London or Surrey we would fit an approved tracker and an immobiliser together, and most insurers at that value ask for both."),
       ("Will this affect my Mercedes warranty or service plan?",
        "No. We fit to manufacturer standard using factory feeds and manufacturer connector standards, with nothing cut or spliced. Warranty and service plans are unaffected.")]),

"audi": dict(
 name="Audi",
 models="RS3, RS4, RS6, RS Q8, Q7, Q8, A6, A8 and the e-tron range",
 intro="Audi theft splits between the RS cars, taken because of what they are, and the Q7, Q8 and e-tron SUVs, taken because they are large, keyless and easy to move. The RS6 in particular has a following among people who should not have one. Most of the cars we protect sit on a drive in a London or Surrey postcode with the keys somewhere in the house, which is the configuration relay attack was designed for.",
 threat="Relay attack is the dominant method and works on any keyless Audi. Audi's keys are also on the VAG platform's shared architecture, which means the security research and the tooling that exists for one Volkswagen Group car tends to be applicable across several - not a reason for alarm, but a reason not to rely on the key alone. An immobiliser adds a step that no amount of key work provides: without the correct sequence, the car does not start regardless of what the network has been told.",
 fitting="Audis are clean cars to work on. The CAN architecture takes a Ghost II properly, trim releases predictably, and there are sensible factory routes to use. We take factory feeds with manufacturer connector standards and cut nothing, so warranty and Audi service plans are unaffected. On RS models with the sports seats and the lower centre console, access takes longer, and on the e-tron cars we work to the high-voltage safety procedure - which does not complicate the tracker but does mean we do not rush.",
 rec=[("Autowatch Ghost II","for an RS car or a Q7/Q8 on a drive - no fob, nothing visible, relay-proof."),
      ("Meta Trak S5 Deadlock","approved tracking with deadlock immobilisation where the insurer specifies both."),
      ("Tracker &amp; immobiliser package","our standard recommendation for an RS6 or RS Q8 in London or Surrey."),
      ("Front and rear dash camera","RS cars attract attention parked as much as moving.")],
 faqs=[("Is an RS6 harder to protect than a Q7?",
        "No - the same methods apply to both, because both are keyless. The RS6 is simply wanted more, which is a reason to fit the immobiliser rather than a reason it cannot be protected. On either car we would fit an approved tracker and an immobiliser together."),
       ("Does the shared Volkswagen Group platform matter?",
        "A little. Research and tooling that exists for one VAG car tends to apply across several, which is a reason not to rely on the key alone rather than a cause for alarm. An immobiliser adds a step no key work provides: no sequence, no start."),
       ("Can you fit to an e-tron safely?",
        "Yes. We work to the high-voltage safety procedure on the electric cars. It does not complicate the tracker installation itself, but it does mean we do not rush the job, and we would rather book the extra time than cut it short.")]),
}
